// Package events provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package events

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApiKeyMode.
const (
	ApiKeyModeLIVE ApiKeyMode = "LIVE"
	ApiKeyModeTEST ApiKeyMode = "TEST"
)

// Valid indicates whether the value is a known member of the ApiKeyMode enum.
func (e ApiKeyMode) Valid() bool {
	switch e {
	case ApiKeyModeLIVE:
		return true
	case ApiKeyModeTEST:
		return true
	default:
		return false
	}
}

// Defines values for ApiKeyCreateMode.
const (
	ApiKeyCreateModeLIVE ApiKeyCreateMode = "LIVE"
	ApiKeyCreateModeTEST ApiKeyCreateMode = "TEST"
)

// Valid indicates whether the value is a known member of the ApiKeyCreateMode enum.
func (e ApiKeyCreateMode) Valid() bool {
	switch e {
	case ApiKeyCreateModeLIVE:
		return true
	case ApiKeyCreateModeTEST:
		return true
	default:
		return false
	}
}

// Defines values for ApiKeyCreateScopes.
const (
	CustomersRead  ApiKeyCreateScopes = "customers:read"
	CustomersWrite ApiKeyCreateScopes = "customers:write"
	InvoicesRead   ApiKeyCreateScopes = "invoices:read"
	InvoicesWrite  ApiKeyCreateScopes = "invoices:write"
	PaymentsRead   ApiKeyCreateScopes = "payments:read"
	PaymentsWrite  ApiKeyCreateScopes = "payments:write"
	UsageWrite     ApiKeyCreateScopes = "usage:write"
	WebhooksRead   ApiKeyCreateScopes = "webhooks:read"
)

// Valid indicates whether the value is a known member of the ApiKeyCreateScopes enum.
func (e ApiKeyCreateScopes) Valid() bool {
	switch e {
	case CustomersRead:
		return true
	case CustomersWrite:
		return true
	case InvoicesRead:
		return true
	case InvoicesWrite:
		return true
	case PaymentsRead:
		return true
	case PaymentsWrite:
		return true
	case UsageWrite:
		return true
	case WebhooksRead:
		return true
	default:
		return false
	}
}

// Defines values for ApiKeyCreatedMode.
const (
	ApiKeyCreatedModeLIVE ApiKeyCreatedMode = "LIVE"
	ApiKeyCreatedModeTEST ApiKeyCreatedMode = "TEST"
)

// Valid indicates whether the value is a known member of the ApiKeyCreatedMode enum.
func (e ApiKeyCreatedMode) Valid() bool {
	switch e {
	case ApiKeyCreatedModeLIVE:
		return true
	case ApiKeyCreatedModeTEST:
		return true
	default:
		return false
	}
}

// Defines values for AttentionItemKind.
const (
	ENDPOINTDISABLED AttentionItemKind = "ENDPOINT_DISABLED"
	INVOICEOVERDUE   AttentionItemKind = "INVOICE_OVERDUE"
	PAYMENTSFAILED   AttentionItemKind = "PAYMENTS_FAILED"
	TRIALENDING      AttentionItemKind = "TRIAL_ENDING"
)

// Valid indicates whether the value is a known member of the AttentionItemKind enum.
func (e AttentionItemKind) Valid() bool {
	switch e {
	case ENDPOINTDISABLED:
		return true
	case INVOICEOVERDUE:
		return true
	case PAYMENTSFAILED:
		return true
	case TRIALENDING:
		return true
	default:
		return false
	}
}

// Defines values for CancelRequestAt.
const (
	NOW       CancelRequestAt = "NOW"
	PERIODEND CancelRequestAt = "PERIOD_END"
)

// Valid indicates whether the value is a known member of the CancelRequestAt enum.
func (e CancelRequestAt) Valid() bool {
	switch e {
	case NOW:
		return true
	case PERIODEND:
		return true
	default:
		return false
	}
}

// Defines values for CustomerStatus.
const (
	CustomerStatusACTIVE   CustomerStatus = "ACTIVE"
	CustomerStatusCHURNED  CustomerStatus = "CHURNED"
	CustomerStatusPASTDUE  CustomerStatus = "PAST_DUE"
	CustomerStatusTRIALING CustomerStatus = "TRIALING"
)

// Valid indicates whether the value is a known member of the CustomerStatus enum.
func (e CustomerStatus) Valid() bool {
	switch e {
	case CustomerStatusACTIVE:
		return true
	case CustomerStatusCHURNED:
		return true
	case CustomerStatusPASTDUE:
		return true
	case CustomerStatusTRIALING:
		return true
	default:
		return false
	}
}

// Defines values for DataExportStatus.
const (
	EXPIRED DataExportStatus = "EXPIRED"
	QUEUED  DataExportStatus = "QUEUED"
	READY   DataExportStatus = "READY"
	RUNNING DataExportStatus = "RUNNING"
)

// Valid indicates whether the value is a known member of the DataExportStatus enum.
func (e DataExportStatus) Valid() bool {
	switch e {
	case EXPIRED:
		return true
	case QUEUED:
		return true
	case READY:
		return true
	case RUNNING:
		return true
	default:
		return false
	}
}

// Defines values for ImpersonationSessionMode.
const (
	READONLY ImpersonationSessionMode = "READ_ONLY"
	WRITE    ImpersonationSessionMode = "WRITE"
)

// Valid indicates whether the value is a known member of the ImpersonationSessionMode enum.
func (e ImpersonationSessionMode) Valid() bool {
	switch e {
	case READONLY:
		return true
	case WRITE:
		return true
	default:
		return false
	}
}

// Defines values for InvitationCreateRole.
const (
	InvitationCreateRoleADMIN     InvitationCreateRole = "ADMIN"
	InvitationCreateRoleDEVELOPER InvitationCreateRole = "DEVELOPER"
	InvitationCreateRoleFINANCE   InvitationCreateRole = "FINANCE"
	InvitationCreateRoleVIEWER    InvitationCreateRole = "VIEWER"
)

// Valid indicates whether the value is a known member of the InvitationCreateRole enum.
func (e InvitationCreateRole) Valid() bool {
	switch e {
	case InvitationCreateRoleADMIN:
		return true
	case InvitationCreateRoleDEVELOPER:
		return true
	case InvitationCreateRoleFINANCE:
		return true
	case InvitationCreateRoleVIEWER:
		return true
	default:
		return false
	}
}

// Defines values for InvoiceStatus.
const (
	DRAFT         InvoiceStatus = "DRAFT"
	OPEN          InvoiceStatus = "OPEN"
	PAID          InvoiceStatus = "PAID"
	UNCOLLECTIBLE InvoiceStatus = "UNCOLLECTIBLE"
	VOID          InvoiceStatus = "VOID"
)

// Valid indicates whether the value is a known member of the InvoiceStatus enum.
func (e InvoiceStatus) Valid() bool {
	switch e {
	case DRAFT:
		return true
	case OPEN:
		return true
	case PAID:
		return true
	case UNCOLLECTIBLE:
		return true
	case VOID:
		return true
	default:
		return false
	}
}

// Defines values for MeActiveTenantRole.
const (
	MeActiveTenantRoleADMIN     MeActiveTenantRole = "ADMIN"
	MeActiveTenantRoleDEVELOPER MeActiveTenantRole = "DEVELOPER"
	MeActiveTenantRoleFINANCE   MeActiveTenantRole = "FINANCE"
	MeActiveTenantRoleOWNER     MeActiveTenantRole = "OWNER"
	MeActiveTenantRoleVIEWER    MeActiveTenantRole = "VIEWER"
)

// Valid indicates whether the value is a known member of the MeActiveTenantRole enum.
func (e MeActiveTenantRole) Valid() bool {
	switch e {
	case MeActiveTenantRoleADMIN:
		return true
	case MeActiveTenantRoleDEVELOPER:
		return true
	case MeActiveTenantRoleFINANCE:
		return true
	case MeActiveTenantRoleOWNER:
		return true
	case MeActiveTenantRoleVIEWER:
		return true
	default:
		return false
	}
}

// Defines values for MeterAggregation.
const (
	MeterAggregationMAX         MeterAggregation = "MAX"
	MeterAggregationSUM         MeterAggregation = "SUM"
	MeterAggregationUNIQUECOUNT MeterAggregation = "UNIQUE_COUNT"
)

// Valid indicates whether the value is a known member of the MeterAggregation enum.
func (e MeterAggregation) Valid() bool {
	switch e {
	case MeterAggregationMAX:
		return true
	case MeterAggregationSUM:
		return true
	case MeterAggregationUNIQUECOUNT:
		return true
	default:
		return false
	}
}

// Defines values for MeterLateEventPolicy.
const (
	MeterLateEventPolicyNEXTPERIOD MeterLateEventPolicy = "NEXT_PERIOD"
	MeterLateEventPolicyREJECT     MeterLateEventPolicy = "REJECT"
)

// Valid indicates whether the value is a known member of the MeterLateEventPolicy enum.
func (e MeterLateEventPolicy) Valid() bool {
	switch e {
	case MeterLateEventPolicyNEXTPERIOD:
		return true
	case MeterLateEventPolicyREJECT:
		return true
	default:
		return false
	}
}

// Defines values for MeterCreateAggregation.
const (
	MeterCreateAggregationMAX         MeterCreateAggregation = "MAX"
	MeterCreateAggregationSUM         MeterCreateAggregation = "SUM"
	MeterCreateAggregationUNIQUECOUNT MeterCreateAggregation = "UNIQUE_COUNT"
)

// Valid indicates whether the value is a known member of the MeterCreateAggregation enum.
func (e MeterCreateAggregation) Valid() bool {
	switch e {
	case MeterCreateAggregationMAX:
		return true
	case MeterCreateAggregationSUM:
		return true
	case MeterCreateAggregationUNIQUECOUNT:
		return true
	default:
		return false
	}
}

// Defines values for MeterCreateLateEventPolicy.
const (
	MeterCreateLateEventPolicyNEXTPERIOD MeterCreateLateEventPolicy = "NEXT_PERIOD"
	MeterCreateLateEventPolicyREJECT     MeterCreateLateEventPolicy = "REJECT"
)

// Valid indicates whether the value is a known member of the MeterCreateLateEventPolicy enum.
func (e MeterCreateLateEventPolicy) Valid() bool {
	switch e {
	case MeterCreateLateEventPolicyNEXTPERIOD:
		return true
	case MeterCreateLateEventPolicyREJECT:
		return true
	default:
		return false
	}
}

// Defines values for PaymentStatus.
const (
	PaymentStatusFAILED            PaymentStatus = "FAILED"
	PaymentStatusPARTIALLYREFUNDED PaymentStatus = "PARTIALLY_REFUNDED"
	PaymentStatusPROCESSING        PaymentStatus = "PROCESSING"
	PaymentStatusREFUNDED          PaymentStatus = "REFUNDED"
	PaymentStatusSUCCEEDED         PaymentStatus = "SUCCEEDED"
)

// Valid indicates whether the value is a known member of the PaymentStatus enum.
func (e PaymentStatus) Valid() bool {
	switch e {
	case PaymentStatusFAILED:
		return true
	case PaymentStatusPARTIALLYREFUNDED:
		return true
	case PaymentStatusPROCESSING:
		return true
	case PaymentStatusREFUNDED:
		return true
	case PaymentStatusSUCCEEDED:
		return true
	default:
		return false
	}
}

// Defines values for PaymentAttemptOutcome.
const (
	PaymentAttemptOutcomeDECLINED  PaymentAttemptOutcome = "DECLINED"
	PaymentAttemptOutcomeERROR     PaymentAttemptOutcome = "ERROR"
	PaymentAttemptOutcomeSUCCEEDED PaymentAttemptOutcome = "SUCCEEDED"
	PaymentAttemptOutcomeTIMEOUT   PaymentAttemptOutcome = "TIMEOUT"
)

// Valid indicates whether the value is a known member of the PaymentAttemptOutcome enum.
func (e PaymentAttemptOutcome) Valid() bool {
	switch e {
	case PaymentAttemptOutcomeDECLINED:
		return true
	case PaymentAttemptOutcomeERROR:
		return true
	case PaymentAttemptOutcomeSUCCEEDED:
		return true
	case PaymentAttemptOutcomeTIMEOUT:
		return true
	default:
		return false
	}
}

// Defines values for PaymentMethodType.
const (
	ACH  PaymentMethodType = "ACH"
	CARD PaymentMethodType = "CARD"
)

// Valid indicates whether the value is a known member of the PaymentMethodType enum.
func (e PaymentMethodType) Valid() bool {
	switch e {
	case ACH:
		return true
	case CARD:
		return true
	default:
		return false
	}
}

// Defines values for PaymentMethodSetupProcessor.
const (
	SIMULATOR  PaymentMethodSetupProcessor = "SIMULATOR"
	STRIPETEST PaymentMethodSetupProcessor = "STRIPE_TEST"
)

// Valid indicates whether the value is a known member of the PaymentMethodSetupProcessor enum.
func (e PaymentMethodSetupProcessor) Valid() bool {
	switch e {
	case SIMULATOR:
		return true
	case STRIPETEST:
		return true
	default:
		return false
	}
}

// Defines values for PriceInterval.
const (
	PriceIntervalMONTH PriceInterval = "MONTH"
	PriceIntervalYEAR  PriceInterval = "YEAR"
)

// Valid indicates whether the value is a known member of the PriceInterval enum.
func (e PriceInterval) Valid() bool {
	switch e {
	case PriceIntervalMONTH:
		return true
	case PriceIntervalYEAR:
		return true
	default:
		return false
	}
}

// Defines values for PriceModel.
const (
	PriceModelFLAT      PriceModel = "FLAT"
	PriceModelGRADUATED PriceModel = "GRADUATED"
	PriceModelPERUNIT   PriceModel = "PER_UNIT"
)

// Valid indicates whether the value is a known member of the PriceModel enum.
func (e PriceModel) Valid() bool {
	switch e {
	case PriceModelFLAT:
		return true
	case PriceModelGRADUATED:
		return true
	case PriceModelPERUNIT:
		return true
	default:
		return false
	}
}

// Defines values for PriceStatus.
const (
	ARCHIVED PriceStatus = "ARCHIVED"
	CURRENT  PriceStatus = "CURRENT"
	LEGACY   PriceStatus = "LEGACY"
)

// Valid indicates whether the value is a known member of the PriceStatus enum.
func (e PriceStatus) Valid() bool {
	switch e {
	case ARCHIVED:
		return true
	case CURRENT:
		return true
	case LEGACY:
		return true
	default:
		return false
	}
}

// Defines values for PriceCreateInterval.
const (
	PriceCreateIntervalMONTH PriceCreateInterval = "MONTH"
	PriceCreateIntervalYEAR  PriceCreateInterval = "YEAR"
)

// Valid indicates whether the value is a known member of the PriceCreateInterval enum.
func (e PriceCreateInterval) Valid() bool {
	switch e {
	case PriceCreateIntervalMONTH:
		return true
	case PriceCreateIntervalYEAR:
		return true
	default:
		return false
	}
}

// Defines values for PriceCreateModel.
const (
	PriceCreateModelFLAT      PriceCreateModel = "FLAT"
	PriceCreateModelGRADUATED PriceCreateModel = "GRADUATED"
	PriceCreateModelPERUNIT   PriceCreateModel = "PER_UNIT"
)

// Valid indicates whether the value is a known member of the PriceCreateModel enum.
func (e PriceCreateModel) Valid() bool {
	switch e {
	case PriceCreateModelFLAT:
		return true
	case PriceCreateModelGRADUATED:
		return true
	case PriceCreateModelPERUNIT:
		return true
	default:
		return false
	}
}

// Defines values for ProductKind.
const (
	ProductKindFLAT    ProductKind = "FLAT"
	ProductKindMETERED ProductKind = "METERED"
	ProductKindSEAT    ProductKind = "SEAT"
)

// Valid indicates whether the value is a known member of the ProductKind enum.
func (e ProductKind) Valid() bool {
	switch e {
	case ProductKindFLAT:
		return true
	case ProductKindMETERED:
		return true
	case ProductKindSEAT:
		return true
	default:
		return false
	}
}

// Defines values for ProductCreateKind.
const (
	ProductCreateKindFLAT    ProductCreateKind = "FLAT"
	ProductCreateKindMETERED ProductCreateKind = "METERED"
	ProductCreateKindSEAT    ProductCreateKind = "SEAT"
)

// Valid indicates whether the value is a known member of the ProductCreateKind enum.
func (e ProductCreateKind) Valid() bool {
	switch e {
	case ProductCreateKindFLAT:
		return true
	case ProductCreateKindMETERED:
		return true
	case ProductCreateKindSEAT:
		return true
	default:
		return false
	}
}

// Defines values for RefundStatus.
const (
	RefundStatusFAILED    RefundStatus = "FAILED"
	RefundStatusPENDING   RefundStatus = "PENDING"
	RefundStatusSUCCEEDED RefundStatus = "SUCCEEDED"
)

// Valid indicates whether the value is a known member of the RefundStatus enum.
func (e RefundStatus) Valid() bool {
	switch e {
	case RefundStatusFAILED:
		return true
	case RefundStatusPENDING:
		return true
	case RefundStatusSUCCEEDED:
		return true
	default:
		return false
	}
}

// Defines values for RevenueSeriesRange.
const (
	RevenueSeriesRangeN12M RevenueSeriesRange = "12M"
	RevenueSeriesRangeN30D RevenueSeriesRange = "30D"
	RevenueSeriesRangeN7D  RevenueSeriesRange = "7D"
)

// Valid indicates whether the value is a known member of the RevenueSeriesRange enum.
func (e RevenueSeriesRange) Valid() bool {
	switch e {
	case RevenueSeriesRangeN12M:
		return true
	case RevenueSeriesRangeN30D:
		return true
	case RevenueSeriesRangeN7D:
		return true
	default:
		return false
	}
}

// Defines values for SubscriptionStatus.
const (
	SubscriptionStatusACTIVE   SubscriptionStatus = "ACTIVE"
	SubscriptionStatusCANCELED SubscriptionStatus = "CANCELED"
	SubscriptionStatusPASTDUE  SubscriptionStatus = "PAST_DUE"
	SubscriptionStatusTRIALING SubscriptionStatus = "TRIALING"
)

// Valid indicates whether the value is a known member of the SubscriptionStatus enum.
func (e SubscriptionStatus) Valid() bool {
	switch e {
	case SubscriptionStatusACTIVE:
		return true
	case SubscriptionStatusCANCELED:
		return true
	case SubscriptionStatusPASTDUE:
		return true
	case SubscriptionStatusTRIALING:
		return true
	default:
		return false
	}
}

// Defines values for SubscriptionUpdateProration.
const (
	CREATEPRORATIONS SubscriptionUpdateProration = "CREATE_PRORATIONS"
	NONE             SubscriptionUpdateProration = "NONE"
)

// Valid indicates whether the value is a known member of the SubscriptionUpdateProration enum.
func (e SubscriptionUpdateProration) Valid() bool {
	switch e {
	case CREATEPRORATIONS:
		return true
	case NONE:
		return true
	default:
		return false
	}
}

// Defines values for TeamMemberRole.
const (
	TeamMemberRoleADMIN     TeamMemberRole = "ADMIN"
	TeamMemberRoleDEVELOPER TeamMemberRole = "DEVELOPER"
	TeamMemberRoleFINANCE   TeamMemberRole = "FINANCE"
	TeamMemberRoleOWNER     TeamMemberRole = "OWNER"
	TeamMemberRoleVIEWER    TeamMemberRole = "VIEWER"
)

// Valid indicates whether the value is a known member of the TeamMemberRole enum.
func (e TeamMemberRole) Valid() bool {
	switch e {
	case TeamMemberRoleADMIN:
		return true
	case TeamMemberRoleDEVELOPER:
		return true
	case TeamMemberRoleFINANCE:
		return true
	case TeamMemberRoleOWNER:
		return true
	case TeamMemberRoleVIEWER:
		return true
	default:
		return false
	}
}

// Defines values for TeamMemberStatus.
const (
	TeamMemberStatusACTIVE  TeamMemberStatus = "ACTIVE"
	TeamMemberStatusINVITED TeamMemberStatus = "INVITED"
)

// Valid indicates whether the value is a known member of the TeamMemberStatus enum.
func (e TeamMemberStatus) Valid() bool {
	switch e {
	case TeamMemberStatusACTIVE:
		return true
	case TeamMemberStatusINVITED:
		return true
	default:
		return false
	}
}

// Defines values for TeamMemberUpdateRole.
const (
	TeamMemberUpdateRoleADMIN     TeamMemberUpdateRole = "ADMIN"
	TeamMemberUpdateRoleDEVELOPER TeamMemberUpdateRole = "DEVELOPER"
	TeamMemberUpdateRoleFINANCE   TeamMemberUpdateRole = "FINANCE"
	TeamMemberUpdateRoleVIEWER    TeamMemberUpdateRole = "VIEWER"
)

// Valid indicates whether the value is a known member of the TeamMemberUpdateRole enum.
func (e TeamMemberUpdateRole) Valid() bool {
	switch e {
	case TeamMemberUpdateRoleADMIN:
		return true
	case TeamMemberUpdateRoleDEVELOPER:
		return true
	case TeamMemberUpdateRoleFINANCE:
		return true
	case TeamMemberUpdateRoleVIEWER:
		return true
	default:
		return false
	}
}

// Defines values for WebhookDeliveryStatus.
const (
	WebhookDeliveryStatusDEADLETTERED WebhookDeliveryStatus = "DEAD_LETTERED"
	WebhookDeliveryStatusDELIVERED    WebhookDeliveryStatus = "DELIVERED"
	WebhookDeliveryStatusFAILED       WebhookDeliveryStatus = "FAILED"
	WebhookDeliveryStatusHELD         WebhookDeliveryStatus = "HELD"
	WebhookDeliveryStatusRETRYING     WebhookDeliveryStatus = "RETRYING"
)

// Valid indicates whether the value is a known member of the WebhookDeliveryStatus enum.
func (e WebhookDeliveryStatus) Valid() bool {
	switch e {
	case WebhookDeliveryStatusDEADLETTERED:
		return true
	case WebhookDeliveryStatusDELIVERED:
		return true
	case WebhookDeliveryStatusFAILED:
		return true
	case WebhookDeliveryStatusHELD:
		return true
	case WebhookDeliveryStatusRETRYING:
		return true
	default:
		return false
	}
}

// Defines values for WebhookEndpointStatus.
const (
	WebhookEndpointStatusCIRCUITOPEN WebhookEndpointStatus = "CIRCUIT_OPEN"
	WebhookEndpointStatusDEGRADED    WebhookEndpointStatus = "DEGRADED"
	WebhookEndpointStatusDISABLED    WebhookEndpointStatus = "DISABLED"
	WebhookEndpointStatusENABLED     WebhookEndpointStatus = "ENABLED"
)

// Valid indicates whether the value is a known member of the WebhookEndpointStatus enum.
func (e WebhookEndpointStatus) Valid() bool {
	switch e {
	case WebhookEndpointStatusCIRCUITOPEN:
		return true
	case WebhookEndpointStatusDEGRADED:
		return true
	case WebhookEndpointStatusDISABLED:
		return true
	case WebhookEndpointStatusENABLED:
		return true
	default:
		return false
	}
}

// Defines values for WebhookEndpointCreatedStatus.
const (
	WebhookEndpointCreatedStatusCIRCUITOPEN WebhookEndpointCreatedStatus = "CIRCUIT_OPEN"
	WebhookEndpointCreatedStatusDEGRADED    WebhookEndpointCreatedStatus = "DEGRADED"
	WebhookEndpointCreatedStatusDISABLED    WebhookEndpointCreatedStatus = "DISABLED"
	WebhookEndpointCreatedStatusENABLED     WebhookEndpointCreatedStatus = "ENABLED"
)

// Valid indicates whether the value is a known member of the WebhookEndpointCreatedStatus enum.
func (e WebhookEndpointCreatedStatus) Valid() bool {
	switch e {
	case WebhookEndpointCreatedStatusCIRCUITOPEN:
		return true
	case WebhookEndpointCreatedStatusDEGRADED:
		return true
	case WebhookEndpointCreatedStatusDISABLED:
		return true
	case WebhookEndpointCreatedStatusENABLED:
		return true
	default:
		return false
	}
}

// Defines values for ListCustomersParamsSort.
const (
	MinusCreatedAt ListCustomersParamsSort = "-created_at"
	MinusMrr       ListCustomersParamsSort = "-mrr"
	Mrr            ListCustomersParamsSort = "mrr"
)

// Valid indicates whether the value is a known member of the ListCustomersParamsSort enum.
func (e ListCustomersParamsSort) Valid() bool {
	switch e {
	case MinusCreatedAt:
		return true
	case MinusMrr:
		return true
	case Mrr:
		return true
	default:
		return false
	}
}

// Defines values for GetRevenueSeriesParamsRange.
const (
	GetRevenueSeriesParamsRangeN12M GetRevenueSeriesParamsRange = "12M"
	GetRevenueSeriesParamsRangeN30D GetRevenueSeriesParamsRange = "30D"
	GetRevenueSeriesParamsRangeN7D  GetRevenueSeriesParamsRange = "7D"
)

// Valid indicates whether the value is a known member of the GetRevenueSeriesParamsRange enum.
func (e GetRevenueSeriesParamsRange) Valid() bool {
	switch e {
	case GetRevenueSeriesParamsRangeN12M:
		return true
	case GetRevenueSeriesParamsRangeN30D:
		return true
	case GetRevenueSeriesParamsRangeN7D:
		return true
	default:
		return false
	}
}

// AccountPlan defines model for AccountPlan.
type AccountPlan struct {
	Limits []struct {
		Key   string `json:"key"`
		Limit int    `json:"limit"`
		Used  int    `json:"used"`
	} `json:"limits"`
	PlanCode string     `json:"plan_code"`
	RenewsAt *Timestamp `json:"renews_at,omitempty"`
	Version  int        `json:"version"`
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt  Timestamp  `json:"created_at"`
	Id         string     `json:"id"`
	Last4      string     `json:"last4"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	Mode       ApiKeyMode `json:"mode"`
	Name       string     `json:"name"`
	Prefix     string     `json:"prefix"`
	RevokedAt  *time.Time `json:"revoked_at,omitempty"`
	Scopes     []string   `json:"scopes"`
}

// ApiKeyMode defines model for ApiKey.Mode.
type ApiKeyMode string

// ApiKeyCreate defines model for ApiKeyCreate.
type ApiKeyCreate struct {
	Mode   ApiKeyCreateMode     `json:"mode"`
	Name   string               `json:"name"`
	Scopes []ApiKeyCreateScopes `json:"scopes"`
}

// ApiKeyCreateMode defines model for ApiKeyCreate.Mode.
type ApiKeyCreateMode string

// ApiKeyCreateScopes defines model for ApiKeyCreate.Scopes.
type ApiKeyCreateScopes string

// ApiKeyCreated defines model for ApiKeyCreated.
type ApiKeyCreated struct {
	CreatedAt  Timestamp         `json:"created_at"`
	Id         string            `json:"id"`
	Last4      string            `json:"last4"`
	LastUsedAt *time.Time        `json:"last_used_at,omitempty"`
	Mode       ApiKeyCreatedMode `json:"mode"`
	Name       string            `json:"name"`
	Prefix     string            `json:"prefix"`
	RevokedAt  *time.Time        `json:"revoked_at,omitempty"`
	Scopes     []string          `json:"scopes"`

	// Secret Returned exactly once (FR-KEY-01).
	Secret string `json:"secret"`
}

// ApiKeyCreatedMode defines model for ApiKeyCreated.Mode.
type ApiKeyCreatedMode string

// AttentionItem defines model for AttentionItem.
type AttentionItem struct {
	Action struct {
		Label  string `json:"label"`
		Target string `json:"target"`
	} `json:"action"`
	Detail string            `json:"detail"`
	Id     string            `json:"id"`
	Kind   AttentionItemKind `json:"kind"`
	Title  string            `json:"title"`
}

// AttentionItemKind defines model for AttentionItem.Kind.
type AttentionItemKind string

// Branding defines model for Branding.
type Branding struct {
	AccentHex string  `json:"accent_hex"`
	LogoUrl   *string `json:"logo_url,omitempty"`
}

// CancelRequest defines model for CancelRequest.
type CancelRequest struct {
	At CancelRequestAt `json:"at"`
}

// CancelRequestAt defines model for CancelRequest.At.
type CancelRequestAt string

// Customer defines model for Customer.
type Customer struct {
	CreatedAt   Timestamp          `json:"created_at"`
	Currency    string             `json:"currency"`
	Email       string             `json:"email"`
	Id          string             `json:"id"`
	Metadata    *map[string]string `json:"metadata,omitempty"`
	Mrr         *Money             `json:"mrr,omitempty"`
	Name        *string            `json:"name,omitempty"`
	OpenBalance *Money             `json:"open_balance,omitempty"`
	Status      CustomerStatus     `json:"status"`
}

// CustomerStatus defines model for Customer.Status.
type CustomerStatus string

// CustomerCreate defines model for CustomerCreate.
type CustomerCreate struct {
	Currency string              `json:"currency"`
	Email    openapi_types.Email `json:"email"`
	Metadata *map[string]string  `json:"metadata,omitempty"`
	Name     *string             `json:"name,omitempty"`
}

// CustomerUpdate defines model for CustomerUpdate.
type CustomerUpdate struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Metadata *map[string]string   `json:"metadata,omitempty"`
	Name     *string              `json:"name,omitempty"`
}

// DataExport defines model for DataExport.
type DataExport struct {
	DownloadUrl *string          `json:"download_url,omitempty"`
	ExpiresAt   *Timestamp       `json:"expires_at,omitempty"`
	Id          string           `json:"id"`
	Status      DataExportStatus `json:"status"`
}

// DataExportStatus defines model for DataExport.Status.
type DataExportStatus string

// DeliveryAttempt defines model for DeliveryAttempt.
type DeliveryAttempt struct {
	AttemptNo   int       `json:"attempt_no"`
	AttemptedAt Timestamp `json:"attempted_at"`
	Error       *string   `json:"error,omitempty"`
	LatencyMs   *int      `json:"latency_ms,omitempty"`
	StatusCode  *int      `json:"status_code,omitempty"`
	Timing      *struct {
		ConnectMs  *int `json:"connect_ms,omitempty"`
		DnsMs      *int `json:"dns_ms,omitempty"`
		DownloadMs *int `json:"download_ms,omitempty"`
		TlsMs      *int `json:"tls_ms,omitempty"`
		WaitMs     *int `json:"wait_ms,omitempty"`
	} `json:"timing,omitempty"`
}

// EndpointHealth defines model for EndpointHealth.
type EndpointHealth struct {
	EndpointId string `json:"endpoint_id"`
	Hours      []struct {
		Delivered int       `json:"delivered"`
		Failed    int       `json:"failed"`
		Hour      Timestamp `json:"hour"`
	} `json:"hours"`
	NextProbeAt    *time.Time `json:"next_probe_at,omitempty"`
	P95Ms          *int       `json:"p95_ms,omitempty"`
	Status         string     `json:"status"`
	SuccessRate24h float32    `json:"success_rate_24h"`
}

// Event defines model for Event.
type Event struct {
	ApiVersion string                 `json:"api_version"`
	CreatedAt  Timestamp              `json:"created_at"`
	Data       map[string]interface{} `json:"data"`
	Deliveries *[]struct {
		EndpointId string `json:"endpoint_id"`
		Status     string `json:"status"`
	} `json:"deliveries,omitempty"`
	Id   string `json:"id"`
	Type string `json:"type"`
}

// ImpersonationSession defines model for ImpersonationSession.
type ImpersonationSession struct {
	EndedAt      *time.Time               `json:"ended_at,omitempty"`
	Id           string                   `json:"id"`
	Mode         ImpersonationSessionMode `json:"mode"`
	OperatorName string                   `json:"operator_name"`
	Reason       string                   `json:"reason"`
	StartedAt    Timestamp                `json:"started_at"`
	WriteCount   *int                     `json:"write_count,omitempty"`
}

// ImpersonationSessionMode defines model for ImpersonationSession.Mode.
type ImpersonationSessionMode string

// Invitation defines model for Invitation.
type Invitation struct {
	Email     string    `json:"email"`
	ExpiresAt Timestamp `json:"expires_at"`
	Id        string    `json:"id"`
	Role      string    `json:"role"`
}

// InvitationCreate defines model for InvitationCreate.
type InvitationCreate struct {
	Email openapi_types.Email  `json:"email"`
	Role  InvitationCreateRole `json:"role"`
}

// InvitationCreateRole defines model for InvitationCreate.Role.
type InvitationCreateRole string

// Invoice defines model for Invoice.
type Invoice struct {
	AmountDue      Money               `json:"amount_due"`
	CustomerId     string              `json:"customer_id"`
	DueDate        *openapi_types.Date `json:"due_date,omitempty"`
	FinalizedAt    *time.Time          `json:"finalized_at,omitempty"`
	Id             string              `json:"id"`
	Lines          []InvoiceLine       `json:"lines"`
	Number         *string             `json:"number,omitempty"`
	OverdueDays    *int                `json:"overdue_days,omitempty"`
	RemindedAt     *time.Time          `json:"reminded_at,omitempty"`
	Status         InvoiceStatus       `json:"status"`
	SubscriptionId *string             `json:"subscription_id,omitempty"`
	Total          Money               `json:"total"`
	Version        *int                `json:"version,omitempty"`
}

// InvoiceStatus defines model for Invoice.Status.
type InvoiceStatus string

// InvoiceLine defines model for InvoiceLine.
type InvoiceLine struct {
	Amount        Money   `json:"amount"`
	Description   string  `json:"description"`
	Id            string  `json:"id"`
	PriceId       *string `json:"price_id,omitempty"`
	Quantity      int     `json:"quantity"`
	UnitAmount    *int    `json:"unit_amount,omitempty"`
	UsageRollupId *string `json:"usage_rollup_id,omitempty"`
}

// InvoiceLineCreate defines model for InvoiceLineCreate.
type InvoiceLineCreate struct {
	Description string `json:"description"`
	Quantity    int    `json:"quantity"`
	UnitAmount  int    `json:"unit_amount"`
}

// InvoiceSummary defines model for InvoiceSummary.
type InvoiceSummary struct {
	Counts        map[string]int `json:"counts"`
	Outstanding   Money          `json:"outstanding"`
	Overdue       Money          `json:"overdue"`
	PaidThisMonth Money          `json:"paid_this_month"`
}

// InvoiceUpdate defines model for InvoiceUpdate.
type InvoiceUpdate struct {
	DueDate *openapi_types.Date `json:"due_date,omitempty"`
	Memo    *string             `json:"memo,omitempty"`
}

// Me defines model for Me.
type Me struct {
	ActiveTenant struct {
		Id   string             `json:"id"`
		Name string             `json:"name"`
		Role MeActiveTenantRole `json:"role"`
	} `json:"active_tenant"`
	Livemode    *bool `json:"livemode,omitempty"`
	Memberships []struct {
		Role       string `json:"role"`
		TenantId   string `json:"tenant_id"`
		TenantName string `json:"tenant_name"`
	} `json:"memberships"`
	User struct {
		Email string  `json:"email"`
		Id    string  `json:"id"`
		Name  *string `json:"name,omitempty"`
	} `json:"user"`
}

// MeActiveTenantRole defines model for Me.ActiveTenant.Role.
type MeActiveTenantRole string

// Meter defines model for Meter.
type Meter struct {
	Aggregation     MeterAggregation      `json:"aggregation"`
	Id              string                `json:"id"`
	Key             string                `json:"key"`
	LateEventPolicy *MeterLateEventPolicy `json:"late_event_policy,omitempty"`
	Unit            string                `json:"unit"`
}

// MeterAggregation defines model for Meter.Aggregation.
type MeterAggregation string

// MeterLateEventPolicy defines model for Meter.LateEventPolicy.
type MeterLateEventPolicy string

// MeterCreate defines model for MeterCreate.
type MeterCreate struct {
	Aggregation     MeterCreateAggregation      `json:"aggregation"`
	Key             string                      `json:"key"`
	LateEventPolicy *MeterCreateLateEventPolicy `json:"late_event_policy,omitempty"`
	Unit            string                      `json:"unit"`
}

// MeterCreateAggregation defines model for MeterCreate.Aggregation.
type MeterCreateAggregation string

// MeterCreateLateEventPolicy defines model for MeterCreate.LateEventPolicy.
type MeterCreateLateEventPolicy string

// Money defines model for Money.
type Money struct {
	// Amount Minor units. Never a float.
	Amount   int64  `json:"amount"`
	Currency string `json:"currency"`
}

// MrrByPlan defines model for MrrByPlan.
type MrrByPlan struct {
	Plans []struct {
		Mrr               Money  `json:"mrr"`
		Name              string `json:"name"`
		ProductId         string `json:"product_id"`
		SubscriptionCount *int   `json:"subscription_count,omitempty"`
	} `json:"plans"`
	Total Money `json:"total"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount        Money             `json:"amount"`
	Attempts      *[]PaymentAttempt `json:"attempts,omitempty"`
	CreatedAt     Timestamp         `json:"created_at"`
	CustomerId    string            `json:"customer_id"`
	Id            string            `json:"id"`
	InvoiceId     *string           `json:"invoice_id,omitempty"`
	NextRetryAt   *time.Time        `json:"next_retry_at,omitempty"`
	PaymentMethod *PaymentMethod    `json:"payment_method,omitempty"`
	Status        PaymentStatus     `json:"status"`
}

// PaymentStatus defines model for Payment.Status.
type PaymentStatus string

// PaymentAttempt defines model for PaymentAttempt.
type PaymentAttempt struct {
	AttemptNo   int                   `json:"attempt_no"`
	AttemptedAt Timestamp             `json:"attempted_at"`
	FailureCode *string               `json:"failure_code,omitempty"`
	Outcome     PaymentAttemptOutcome `json:"outcome"`
}

// PaymentAttemptOutcome defines model for PaymentAttempt.Outcome.
type PaymentAttemptOutcome string

// PaymentCreate defines model for PaymentCreate.
type PaymentCreate struct {
	Amount          Money   `json:"amount"`
	CustomerId      string  `json:"customer_id"`
	InvoiceId       *string `json:"invoice_id,omitempty"`
	PaymentMethodId string  `json:"payment_method_id"`
}

// PaymentMethod defines model for PaymentMethod.
type PaymentMethod struct {
	Brand    string             `json:"brand"`
	ExpMonth *int               `json:"exp_month,omitempty"`
	ExpYear  *int               `json:"exp_year,omitempty"`
	Id       string             `json:"id"`
	Last4    string             `json:"last4"`
	Type     *PaymentMethodType `json:"type,omitempty"`
}

// PaymentMethodType defines model for PaymentMethod.Type.
type PaymentMethodType string

// PaymentMethodSetup defines model for PaymentMethodSetup.
type PaymentMethodSetup struct {
	ExpiresAt  *Timestamp                  `json:"expires_at,omitempty"`
	Processor  PaymentMethodSetupProcessor `json:"processor"`
	SetupToken string                      `json:"setup_token"`
}

// PaymentMethodSetupProcessor defines model for PaymentMethodSetup.Processor.
type PaymentMethodSetupProcessor string

// PaymentSummary defines model for PaymentSummary.
type PaymentSummary struct {
	CollectedThisMonth Money   `json:"collected_this_month"`
	FailedCount        int     `json:"failed_count"`
	RefundedThisMonth  Money   `json:"refunded_this_month"`
	SuccessRate        float32 `json:"success_rate"`
}

// Price defines model for Price.
type Price struct {
	CreatedAt         *Timestamp     `json:"created_at,omitempty"`
	Currency          string         `json:"currency"`
	Id                string         `json:"id"`
	Interval          *PriceInterval `json:"interval,omitempty"`
	Model             PriceModel     `json:"model"`
	ProductId         string         `json:"product_id"`
	Status            PriceStatus    `json:"status"`
	SubscriptionCount *int           `json:"subscription_count,omitempty"`
	Tiers             *[]PriceTier   `json:"tiers,omitempty"`
	UnitAmount        *int           `json:"unit_amount,omitempty"`
	Version           int            `json:"version"`
}

// PriceInterval defines model for Price.Interval.
type PriceInterval string

// PriceModel defines model for Price.Model.
type PriceModel string

// PriceStatus defines model for Price.Status.
type PriceStatus string

// PriceCreate defines model for PriceCreate.
type PriceCreate struct {
	Currency   string              `json:"currency"`
	Interval   PriceCreateInterval `json:"interval"`
	Model      PriceCreateModel    `json:"model"`
	Tiers      *[]PriceTier        `json:"tiers,omitempty"`
	UnitAmount *int                `json:"unit_amount,omitempty"`
}

// PriceCreateInterval defines model for PriceCreate.Interval.
type PriceCreateInterval string

// PriceCreateModel defines model for PriceCreate.Model.
type PriceCreateModel string

// PriceTier defines model for PriceTier.
type PriceTier struct {
	FlatAmount *int `json:"flat_amount,omitempty"`
	UnitAmount int  `json:"unit_amount"`
	UpTo       *int `json:"up_to"`
}

// Problem defines model for Problem.
type Problem struct {
	// Code Examples: IDEMPOTENCY_KEY_REUSED
	Code      string  `json:"code"`
	Detail    *string `json:"detail,omitempty"`
	Param     *string `json:"param,omitempty"`
	RequestId string  `json:"request_id"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// Product defines model for Product.
type Product struct {
	Active            bool        `json:"active"`
	Id                string      `json:"id"`
	Kind              ProductKind `json:"kind"`
	Name              string      `json:"name"`
	SubscriptionCount *int        `json:"subscription_count,omitempty"`
}

// ProductKind defines model for Product.Kind.
type ProductKind string

// ProductCreate defines model for ProductCreate.
type ProductCreate struct {
	Kind ProductCreateKind `json:"kind"`
	Name string            `json:"name"`
}

// ProductCreateKind defines model for ProductCreate.Kind.
type ProductCreateKind string

// Refund defines model for Refund.
type Refund struct {
	Amount    Money        `json:"amount"`
	CreatedAt *Timestamp   `json:"created_at,omitempty"`
	Id        string       `json:"id"`
	PaymentId string       `json:"payment_id"`
	Reason    *string      `json:"reason,omitempty"`
	Status    RefundStatus `json:"status"`
}

// RefundStatus defines model for Refund.Status.
type RefundStatus string

// RefundCreate defines model for RefundCreate.
type RefundCreate struct {
	Amount    Money  `json:"amount"`
	PaymentId string `json:"payment_id"`
	Reason    string `json:"reason"`
}

// ReminderAccepted defines model for ReminderAccepted.
type ReminderAccepted struct {
	Accepted int `json:"accepted"`
	Skipped  []struct {
		InvoiceId string `json:"invoice_id"`
		Reason    string `json:"reason"`
	} `json:"skipped"`
}

// ReminderRequest defines model for ReminderRequest.
type ReminderRequest struct {
	InvoiceIds []string `json:"invoice_ids"`
}

// ReportSummary defines model for ReportSummary.
type ReportSummary struct {
	ActiveSubscriptions     *int   `json:"active_subscriptions,omitempty"`
	FailedPayments7d        int    `json:"failed_payments_7d"`
	Mrr                     Money  `json:"mrr"`
	Outstanding             Money  `json:"outstanding"`
	OutstandingInvoiceCount *int   `json:"outstanding_invoice_count,omitempty"`
	Overdue                 *Money `json:"overdue,omitempty"`
	RevenuePrevMonth        *Money `json:"revenue_prev_month,omitempty"`
	RevenueThisMonth        Money  `json:"revenue_this_month"`
}

// RequestLog defines model for RequestLog.
type RequestLog struct {
	ApiKeyName *string   `json:"api_key_name,omitempty"`
	LatencyMs  int       `json:"latency_ms"`
	Method     string    `json:"method"`
	Path       string    `json:"path"`
	RequestId  *string   `json:"request_id,omitempty"`
	Status     int       `json:"status"`
	Ts         Timestamp `json:"ts"`
}

// RevenueSeries defines model for RevenueSeries.
type RevenueSeries struct {
	Points []struct {
		Amount int                `json:"amount"`
		Date   openapi_types.Date `json:"date"`
	} `json:"points"`
	Range RevenueSeriesRange `json:"range"`
	Total Money              `json:"total"`
}

// RevenueSeriesRange defines model for RevenueSeries.Range.
type RevenueSeriesRange string

// Subscription defines model for Subscription.
type Subscription struct {
	CancelAtPeriodEnd  *bool              `json:"cancel_at_period_end,omitempty"`
	CurrentPeriodEnd   Timestamp          `json:"current_period_end"`
	CurrentPeriodStart Timestamp          `json:"current_period_start"`
	CustomerId         string             `json:"customer_id"`
	Id                 string             `json:"id"`
	Items              []SubscriptionItem `json:"items"`
	Mrr                *Money             `json:"mrr,omitempty"`
	Status             SubscriptionStatus `json:"status"`
	TrialEnd           *time.Time         `json:"trial_end,omitempty"`
	Version            *int               `json:"version,omitempty"`
}

// SubscriptionStatus defines model for Subscription.Status.
type SubscriptionStatus string

// SubscriptionCreate defines model for SubscriptionCreate.
type SubscriptionCreate struct {
	CustomerId string             `json:"customer_id"`
	Items      []SubscriptionItem `json:"items"`
	TrialDays  *int               `json:"trial_days,omitempty"`
}

// SubscriptionItem defines model for SubscriptionItem.
type SubscriptionItem struct {
	Id       *string `json:"id,omitempty"`
	PriceId  string  `json:"price_id"`
	Quantity int     `json:"quantity"`
}

// SubscriptionPreview defines model for SubscriptionPreview.
type SubscriptionPreview struct {
	DueToday    Money  `json:"due_today"`
	Explanation string `json:"explanation"`
	Lines       []struct {
		Amount      Money  `json:"amount"`
		Description string `json:"description"`
		Proration   *bool  `json:"proration,omitempty"`
	} `json:"lines"`
	RecurringTotal Money `json:"recurring_total"`
}

// SubscriptionPreviewRequest defines model for SubscriptionPreviewRequest.
type SubscriptionPreviewRequest struct {
	CustomerId     string             `json:"customer_id"`
	Items          []SubscriptionItem `json:"items"`
	SubscriptionId *string            `json:"subscription_id,omitempty"`
	TrialDays      *int               `json:"trial_days,omitempty"`
}

// SubscriptionUpdate defines model for SubscriptionUpdate.
type SubscriptionUpdate struct {
	Items     *[]SubscriptionItem          `json:"items,omitempty"`
	Proration *SubscriptionUpdateProration `json:"proration,omitempty"`
}

// SubscriptionUpdateProration defines model for SubscriptionUpdate.Proration.
type SubscriptionUpdateProration string

// TeamMember defines model for TeamMember.
type TeamMember struct {
	Email  string           `json:"email"`
	Mfa    *string          `json:"mfa,omitempty"`
	Name   *string          `json:"name,omitempty"`
	Role   TeamMemberRole   `json:"role"`
	Status TeamMemberStatus `json:"status"`
	UserId string           `json:"user_id"`
}

// TeamMemberRole defines model for TeamMember.Role.
type TeamMemberRole string

// TeamMemberStatus defines model for TeamMember.Status.
type TeamMemberStatus string

// TeamMemberUpdate defines model for TeamMemberUpdate.
type TeamMemberUpdate struct {
	Role TeamMemberUpdateRole `json:"role"`
}

// TeamMemberUpdateRole defines model for TeamMemberUpdate.Role.
type TeamMemberUpdateRole string

// TestClock defines model for TestClock.
type TestClock struct {
	FrozenTime      Timestamp `json:"frozen_time"`
	Id              string    `json:"id"`
	SubscriptionIds *[]string `json:"subscription_ids,omitempty"`
}

// TestClockAdvance defines model for TestClockAdvance.
type TestClockAdvance struct {
	To Timestamp `json:"to"`
}

// TimelineEntry defines model for TimelineEntry.
type TimelineEntry struct {
	At       Timestamp `json:"at"`
	Kind     string    `json:"kind"`
	ObjectId *string   `json:"object_id,omitempty"`
	Title    string    `json:"title"`
}

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// UsageAccepted defines model for UsageAccepted.
type UsageAccepted struct {
	Accepted   int `json:"accepted"`
	Duplicates int `json:"duplicates"`
}

// UsageBatch defines model for UsageBatch.
type UsageBatch struct {
	Events []UsageEvent `json:"events"`
}

// UsageEvent defines model for UsageEvent.
type UsageEvent struct {
	CustomerId string    `json:"customer_id"`
	EventId    string    `json:"event_id"`
	Meter      string    `json:"meter"`
	OccurredAt Timestamp `json:"occurred_at"`
	Quantity   float32   `json:"quantity"`
}

// UsageSummary defines model for UsageSummary.
type UsageSummary struct {
	Actual                 float32   `json:"actual"`
	Included               float32   `json:"included"`
	Meter                  string    `json:"meter"`
	PeriodEnd              Timestamp `json:"period_end"`
	PeriodStart            Timestamp `json:"period_start"`
	Projected              float32   `json:"projected"`
	ProjectedOverageCharge *Money    `json:"projected_overage_charge,omitempty"`
	Series                 *[]struct {
		Cumulative float32            `json:"cumulative"`
		Date       openapi_types.Date `json:"date"`
		Projected  *bool              `json:"projected,omitempty"`
	} `json:"series,omitempty"`
}

// WebhookDelivery defines model for WebhookDelivery.
type WebhookDelivery struct {
	AttemptCount   *int                  `json:"attempt_count,omitempty"`
	Attempts       []DeliveryAttempt     `json:"attempts"`
	EndpointId     string                `json:"endpoint_id"`
	EventId        string                `json:"event_id"`
	EventType      string                `json:"event_type"`
	Id             string                `json:"id"`
	NextAttemptAt  *time.Time            `json:"next_attempt_at,omitempty"`
	ReplayOf       *string               `json:"replay_of,omitempty"`
	RequestHeaders *map[string]string    `json:"request_headers,omitempty"`
	ResponseStatus *int                  `json:"response_status,omitempty"`
	Status         WebhookDeliveryStatus `json:"status"`
}

// WebhookDeliveryStatus defines model for WebhookDelivery.Status.
type WebhookDeliveryStatus string

// WebhookEndpoint defines model for WebhookEndpoint.
type WebhookEndpoint struct {
	DisabledAt    *time.Time            `json:"disabled_at,omitempty"`
	EventTypes    []string              `json:"event_types"`
	FailureStreak *int                  `json:"failure_streak,omitempty"`
	Id            string                `json:"id"`
	Status        WebhookEndpointStatus `json:"status"`
	Url           string                `json:"url"`
	Version       *int                  `json:"version,omitempty"`
}

// WebhookEndpointStatus defines model for WebhookEndpoint.Status.
type WebhookEndpointStatus string

// WebhookEndpointCreate defines model for WebhookEndpointCreate.
type WebhookEndpointCreate struct {
	EventTypes []string `json:"event_types"`
	Url        string   `json:"url"`
}

// WebhookEndpointCreated defines model for WebhookEndpointCreated.
type WebhookEndpointCreated struct {
	DisabledAt    *time.Time                   `json:"disabled_at,omitempty"`
	EventTypes    []string                     `json:"event_types"`
	FailureStreak *int                         `json:"failure_streak,omitempty"`
	Id            string                       `json:"id"`
	Secret        string                       `json:"secret"`
	Status        WebhookEndpointCreatedStatus `json:"status"`
	Url           string                       `json:"url"`
	Version       *int                         `json:"version,omitempty"`
}

// WebhookEndpointCreatedStatus defines model for WebhookEndpointCreated.Status.
type WebhookEndpointCreatedStatus string

// WebhookEndpointUpdate defines model for WebhookEndpointUpdate.
type WebhookEndpointUpdate struct {
	EventTypes *[]string `json:"event_types,omitempty"`
	Url        *string   `json:"url,omitempty"`
}

// WebhookSecret defines model for WebhookSecret.
type WebhookSecret struct {
	OverlapUntil *time.Time `json:"overlap_until"`
	Secret       string     `json:"secret"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// Limit defines model for Limit.
type Limit = int

// StartingAfter defines model for StartingAfter.
type StartingAfter = string

// RequestDataExportParams defines parameters for RequestDataExport.
type RequestDataExportParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListImpersonationSessionsParams defines parameters for ListImpersonationSessions.
type ListImpersonationSessionsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
}

// ListApiKeysParams defines parameters for ListApiKeys.
type ListApiKeysParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
}

// CreateApiKeyParams defines parameters for CreateApiKey.
type CreateApiKeyParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListAttentionItemsParams defines parameters for ListAttentionItems.
type ListAttentionItemsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
}

// ListCustomersParams defines parameters for ListCustomers.
type ListCustomersParams struct {
	Limit         *Limit                   `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter           `form:"starting_after,omitempty" json:"starting_after,omitempty"`
	Q             *string                  `form:"q,omitempty" json:"q,omitempty"`
	Status        *string                  `form:"status,omitempty" json:"status,omitempty"`
	Sort          *ListCustomersParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListCustomersParamsSort defines parameters for ListCustomers.
type ListCustomersParamsSort string

// CreateCustomerParams defines parameters for CreateCustomer.
type CreateCustomerParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateCustomerParams defines parameters for UpdateCustomer.
type UpdateCustomerParams struct {
	// IfMatch ETag from the last read; 412 on mismatch.
	IfMatch IfMatch `json:"If-Match"`
}

// CreatePaymentMethodSetupParams defines parameters for CreatePaymentMethodSetup.
type CreatePaymentMethodSetupParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListPaymentMethodsParams defines parameters for ListPaymentMethods.
type ListPaymentMethodsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
}

// GetCustomerTimelineParams defines parameters for GetCustomerTimeline.
type GetCustomerTimelineParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
}

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
	Type          *string        `form:"type,omitempty" json:"type,omitempty"`
}

// ListInvoicesParams defines parameters for ListInvoices.
type ListInvoicesParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
	Status        *string        `form:"status,omitempty" json:"status,omitempty"`
}

// SendInvoiceRemindersParams defines parameters for SendInvoiceReminders.
type SendInvoiceRemindersParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateDraftInvoiceParams defines parameters for UpdateDraftInvoice.
type UpdateDraftInvoiceParams struct {
	// IfMatch ETag from the last read; 412 on mismatch.
	IfMatch IfMatch `json:"If-Match"`
}

// FinalizeInvoiceParams defines parameters for FinalizeInvoice.
type FinalizeInvoiceParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// AddInvoiceLineParams defines parameters for AddInvoiceLine.
type AddInvoiceLineParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// VoidInvoiceParams defines parameters for VoidInvoice.
type VoidInvoiceParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListMetersParams defines parameters for ListMeters.
type ListMetersParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
}

// CreateMeterParams defines parameters for CreateMeter.
type CreateMeterParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListPaymentsParams defines parameters for ListPayments.
type ListPaymentsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
	Status        *string        `form:"status,omitempty" json:"status,omitempty"`
}

// CreatePaymentParams defines parameters for CreatePayment.
type CreatePaymentParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetPaymentParams defines parameters for GetPayment.
type GetPaymentParams struct {
	Expand *string `form:"expand,omitempty" json:"expand,omitempty"`
}

// ListProductsParams defines parameters for ListProducts.
type ListProductsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
}

// CreateProductParams defines parameters for CreateProduct.
type CreateProductParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListPricesParams defines parameters for ListPrices.
type ListPricesParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
}

// CreatePriceVersionParams defines parameters for CreatePriceVersion.
type CreatePriceVersionParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListRefundsParams defines parameters for ListRefunds.
type ListRefundsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
}

// CreateRefundParams defines parameters for CreateRefund.
type CreateRefundParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetRevenueSeriesParams defines parameters for GetRevenueSeries.
type GetRevenueSeriesParams struct {
	Range *GetRevenueSeriesParamsRange `form:"range,omitempty" json:"range,omitempty"`
}

// GetRevenueSeriesParamsRange defines parameters for GetRevenueSeries.
type GetRevenueSeriesParamsRange string

// ListRequestLogsParams defines parameters for ListRequestLogs.
type ListRequestLogsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
	Status        *string        `form:"status,omitempty" json:"status,omitempty"`
}

// UpdateBrandingParams defines parameters for UpdateBranding.
type UpdateBrandingParams struct {
	// IfMatch ETag from the last read; 412 on mismatch.
	IfMatch IfMatch `json:"If-Match"`
}

// UploadBrandingLogoMultipartBody defines parameters for UploadBrandingLogo.
type UploadBrandingLogoMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ListSubscriptionsParams defines parameters for ListSubscriptions.
type ListSubscriptionsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
	Status        *string        `form:"status,omitempty" json:"status,omitempty"`
	Plan          *string        `form:"plan,omitempty" json:"plan,omitempty"`
	RenewsWithin  *string        `form:"renews_within,omitempty" json:"renews_within,omitempty"`
}

// CreateSubscriptionParams defines parameters for CreateSubscription.
type CreateSubscriptionParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateSubscriptionParams defines parameters for UpdateSubscription.
type UpdateSubscriptionParams struct {
	// IfMatch ETag from the last read; 412 on mismatch.
	IfMatch IfMatch `json:"If-Match"`
}

// CancelSubscriptionParams defines parameters for CancelSubscription.
type CancelSubscriptionParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateInvitationParams defines parameters for CreateInvitation.
type CreateInvitationParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListTeamMembersParams defines parameters for ListTeamMembers.
type ListTeamMembersParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
}

// CreateTestClockParams defines parameters for CreateTestClock.
type CreateTestClockParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// AdvanceTestClockParams defines parameters for AdvanceTestClock.
type AdvanceTestClockParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetUsageSummaryParams defines parameters for GetUsageSummary.
type GetUsageSummaryParams struct {
	Meter    *string `form:"meter,omitempty" json:"meter,omitempty"`
	Customer *string `form:"customer,omitempty" json:"customer,omitempty"`
}

// ListUsageEventsParams defines parameters for ListUsageEvents.
type ListUsageEventsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
	Meter         *string        `form:"meter,omitempty" json:"meter,omitempty"`
}

// IngestUsageEventsParams defines parameters for IngestUsageEvents.
type IngestUsageEventsParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListWebhookDeliveriesParams defines parameters for ListWebhookDeliveries.
type ListWebhookDeliveriesParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
	Status        *string        `form:"status,omitempty" json:"status,omitempty"`
	Endpoint      *string        `form:"endpoint,omitempty" json:"endpoint,omitempty"`
}

// ReplayWebhookDeliveryParams defines parameters for ReplayWebhookDelivery.
type ReplayWebhookDeliveryParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListWebhookEndpointsParams defines parameters for ListWebhookEndpoints.
type ListWebhookEndpointsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`
}

// CreateWebhookEndpointParams defines parameters for CreateWebhookEndpoint.
type CreateWebhookEndpointParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateWebhookEndpointParams defines parameters for UpdateWebhookEndpoint.
type UpdateWebhookEndpointParams struct {
	// IfMatch ETag from the last read; 412 on mismatch.
	IfMatch IfMatch `json:"If-Match"`
}

// RotateWebhookSecretParams defines parameters for RotateWebhookSecret.
type RotateWebhookSecretParams struct {
	// IdempotencyKey Required on writes; replayed for 24 h (ADR-006).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = ApiKeyCreate

// CreateCustomerJSONRequestBody defines body for CreateCustomer for application/json ContentType.
type CreateCustomerJSONRequestBody = CustomerCreate

// UpdateCustomerJSONRequestBody defines body for UpdateCustomer for application/json ContentType.
type UpdateCustomerJSONRequestBody = CustomerUpdate

// SendInvoiceRemindersJSONRequestBody defines body for SendInvoiceReminders for application/json ContentType.
type SendInvoiceRemindersJSONRequestBody = ReminderRequest

// UpdateDraftInvoiceJSONRequestBody defines body for UpdateDraftInvoice for application/json ContentType.
type UpdateDraftInvoiceJSONRequestBody = InvoiceUpdate

// AddInvoiceLineJSONRequestBody defines body for AddInvoiceLine for application/json ContentType.
type AddInvoiceLineJSONRequestBody = InvoiceLineCreate

// CreateMeterJSONRequestBody defines body for CreateMeter for application/json ContentType.
type CreateMeterJSONRequestBody = MeterCreate

// CreatePaymentJSONRequestBody defines body for CreatePayment for application/json ContentType.
type CreatePaymentJSONRequestBody = PaymentCreate

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = ProductCreate

// CreatePriceVersionJSONRequestBody defines body for CreatePriceVersion for application/json ContentType.
type CreatePriceVersionJSONRequestBody = PriceCreate

// CreateRefundJSONRequestBody defines body for CreateRefund for application/json ContentType.
type CreateRefundJSONRequestBody = RefundCreate

// UpdateBrandingJSONRequestBody defines body for UpdateBranding for application/json ContentType.
type UpdateBrandingJSONRequestBody = Branding

// UploadBrandingLogoMultipartRequestBody defines body for UploadBrandingLogo for multipart/form-data ContentType.
type UploadBrandingLogoMultipartRequestBody UploadBrandingLogoMultipartBody

// CreateSubscriptionJSONRequestBody defines body for CreateSubscription for application/json ContentType.
type CreateSubscriptionJSONRequestBody = SubscriptionCreate

// PreviewSubscriptionJSONRequestBody defines body for PreviewSubscription for application/json ContentType.
type PreviewSubscriptionJSONRequestBody = SubscriptionPreviewRequest

// UpdateSubscriptionJSONRequestBody defines body for UpdateSubscription for application/json ContentType.
type UpdateSubscriptionJSONRequestBody = SubscriptionUpdate

// CancelSubscriptionJSONRequestBody defines body for CancelSubscription for application/json ContentType.
type CancelSubscriptionJSONRequestBody = CancelRequest

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = InvitationCreate

// UpdateTeamMemberJSONRequestBody defines body for UpdateTeamMember for application/json ContentType.
type UpdateTeamMemberJSONRequestBody = TeamMemberUpdate

// CreateTestClockJSONRequestBody defines body for CreateTestClock for application/json ContentType.
type CreateTestClockJSONRequestBody = TestClock

// AdvanceTestClockJSONRequestBody defines body for AdvanceTestClock for application/json ContentType.
type AdvanceTestClockJSONRequestBody = TestClockAdvance

// IngestUsageEventsJSONRequestBody defines body for IngestUsageEvents for application/json ContentType.
type IngestUsageEventsJSONRequestBody = UsageBatch

// CreateWebhookEndpointJSONRequestBody defines body for CreateWebhookEndpoint for application/json ContentType.
type CreateWebhookEndpointJSONRequestBody = WebhookEndpointCreate

// UpdateWebhookEndpointJSONRequestBody defines body for UpdateWebhookEndpoint for application/json ContentType.
type UpdateWebhookEndpointJSONRequestBody = WebhookEndpointUpdate
