#!/usr/bin/env python3
"""Renders docs/adr/ADR-000-template.md and ADR-001..031 from the table below."""
from pathlib import Path
import re
ROOT = Path(__file__).resolve().parents[1]; D = ROOT / "docs" / "adr"
DATE = "2026-09-22"
(D / "ADR-000-template.md").write_text("""# ADR-NNN: <Title>

- **Status:** Proposed | Accepted | Superseded by ADR-xxx
- **Date:** YYYY-MM-DD
- **Deciders:** <names/roles>
- **Related:** <FR/NFR ids, stories, other ADRs>

## Context
<Forces at play, constraints, what problem needs a decision. Numbers where possible.>

## Options considered
1. <Option> — <pros> / <cons>
2. <Option> — <pros> / <cons>

## Decision
<What we do, stated so a reviewer can check code against it.>

## Consequences
<Positive, negative, follow-ups, how we will know it was wrong.>
""")
A = [
 ("001", "Modular monolith core with Go workers", "Accepted", "NFR-MNT-01, TLY-004, TLY-005",
  "Billing logic needs strong consistency across subscriptions, invoices, payments and ledger; delivery and aggregation need high fan-out and independent scaling. One developer maintains everything.",
  ["Microservices per domain — independent deploys / distributed transactions everywhere, heavy ops", "Single monolith incl. workers — simplest / delivery load competes with API latency", "Modular monolith (Spring Modulith) + two Go workers — ACID where money lives, isolation where load differs / two languages"],
  "The core is one Spring Boot deployable with enforced modules; webhook dispatch and usage aggregation are separate Go services connected only by Kafka and a documented internal API.",
  "Local transactions for money flows; module boundaries enforced so extraction stays possible; two toolchains to maintain; cross-service consistency is eventual and designed explicitly (ADR-008, ADR-016)."),
 ("002", "Pool isolation with row-level security by default, silo tier for enterprise", "Accepted", "NFR-SEC-01, FR-TEN-02, TLY-102",
  "Thousands of small tenants must be cheap; a few large tenants may require dedicated storage. Application-only filtering fails silently when a developer forgets a WHERE clause.",
  ["Database per tenant — strongest / costly, migrations × N", "Schema per tenant — medium / catalog bloat at 10k tenants", "Shared tables + tenant_id + RLS FORCE — cheap, DB-enforced / needs disciplined context setting"],
  "All tenants start in the shared pool with `tenant_id` on every table and RLS enabled and forced; the app role has no BYPASSRLS. `isolation_tier` allows moving a tenant to a silo database later (ADR-021).",
  "One schema to migrate; isolation enforced by the database; every connection must set context (ADR-003); noisy neighbors handled at the app layer (ADR-019)."),
 ("003", "Tenant context propagation with ScopedValue and SET LOCAL", "Accepted", "NFR-SEC-02, TLY-102",
  "Virtual threads make ThreadLocal expensive and leak-prone; RLS needs a per-transaction setting that cannot bleed across pooled connections.",
  ["ThreadLocal + session-level SET — familiar / leaks across pooled connections", "Pass tenantId explicitly everywhere — explicit / noisy, easy to forget at the DB edge", "ScopedValue (final in Java 25) + SET LOCAL in each transaction — bounded lifetime, transaction-scoped / requires a connection preparer"],
  "The tenant filter binds `ScopedValue<TenantContext>` from the credential; `TenantConnectionPreparer` issues `SET LOCAL app.tenant_id` at transaction start; `kernel.current_tenant()` returns NULL when unset so queries return nothing.",
  "No context bleed between requests or pooled connections; reads outside transactions are forbidden for tenant tables; background jobs must bind context per tenant explicitly."),
 ("004", "Money as integer minor units", "Accepted", "NFR-COR-04, TLY-201",
  "Floating point cannot represent cents exactly; BigDecimal invites scale mistakes and is slower; JSON numbers are often parsed as doubles by clients.",
  ["double — fast / wrong", "BigDecimal — exact / scale/rounding mistakes, heavier", "long minor units + ISO currency — exact, fast / needs a currency exponent table"],
  "`Money(long minor, Currency)` everywhere; JSON `{amount:int, currency}`; database `bigint` + `char(3)`; rounding only inside the pricing engine with HALF_EVEN.",
  "No rounding drift; ArchUnit forbids double/float/BigDecimal in money packages; zero-decimal and three-decimal currencies handled by the exponent table."),
 ("005", "Append-only double-entry ledger with database-enforced balance", "Accepted", "FR-LED-01..04, NFR-COR-01, TLY-202",
  "Balances derived from mutable columns drift under retries and partial failures; auditors need to see every change.",
  ["Balance columns updated in place — simple / no history, drift", "Event-sourced balances only in code — flexible / invariant only as good as the code", "Double-entry postings, append-only, deferred constraint trigger — invariant in the DB / insert-heavy"],
  "Every money movement is a journal entry with ≥ 2 postings summing to zero per currency, checked by a deferred constraint trigger at commit; postings are never updated or deleted; corrections are reversing entries.",
  "Ledger is the source of truth for money; jOOQ for explicit SQL; balances are queries (cacheable later); property tests guard the invariant."),
 ("006", "Idempotency keys at every boundary", "Accepted", "NFR-COR-03, FR-PAY-01, TLY-110",
  "Clients retry on timeouts; Kafka redelivers; jobs rerun. Without idempotency, retries create duplicate charges and objects.",
  ["Best-effort dedup in code — cheap / inconsistent", "Idempotency keys + stored responses + consumer dedup tables — systematic / storage and cleanup"],
  "Creating/money-moving REST writes require `Idempotency-Key` scoped per tenant, stored with a request hash and response for 24 h; consumers dedupe by event id; jobs by (job, tenant, date); processor calls by payment id + attempt.",
  "Safe retries everywhere; a filter and inbox table to maintain; clear 409/422 semantics documented in docs/04."),
 ("007", "Identity with Keycloak realms, BFF sessions and hashed API keys", "Accepted", "FR-TEN-04, FR-TEN-05, NFR-SEC-04, TLY-103, TLY-104",
  "Tenant users need SSO-style login and tenant switching; machines need API keys; operators need a completely separate identity.",
  ["Build auth in core — control / high risk", "Hosted IdP — easy / cost and less learning", "Keycloak with organizations and token exchange + BFF + hashed API keys — standard protocols / Keycloak ops"],
  "Tenant users authenticate in realm `tally-tenants`; the Next.js BFF keeps tokens server-side and sets an encrypted httpOnly cookie; switching tenant uses token exchange. API keys are prefix + Argon2id hash, cached 5 s. Operators use realm `tally-operators` (ADR-022).",
  "No tokens in the browser; revocation within 5 s; fallback if token exchange misbehaves: core-minted short-lived JWTs (risk register elephant)."),
 ("008", "Transactional outbox with a polling relay", "Accepted", "NFR-COR-02, NFR-PER-06, TLY-301",
  "Publishing to Kafka after commit loses events on crash; publishing before commit invents events on rollback.",
  ["Dual write — simple / loses or invents events", "CDC (Debezium) — low latency / extra infrastructure", "Outbox table + polling relay with SKIP LOCKED — simple, reliable / 100 ms latency, DB load"],
  "Events are inserted into `kernel.outbox_events` in the business transaction; a relay claims batches with `FOR UPDATE SKIP LOCKED`, produces keyed by tenant, then marks them published. The relay reads through a SECURITY DEFINER function, the only RLS exception.",
  "At-least-once publication; consumers must dedupe (ADR-006); CDC remains an upgrade path if lag exceeds NFR-PER-06."),
 ("009", "JSON Schema for event contracts (Protobuf dropped)", "Accepted", "NFR-MNT-04, TLY-003",
  "The earlier design chose Protobuf with a schema registry. Webhook payloads delivered to tenants are JSON anyway, and a registry adds a container to the laptop budget.",
  ["Protobuf + registry — compact, typed / second schema language, extra service", "Avro — evolution rules / same drawbacks", "JSON Schema 2020-12 in contracts/, codegen for Java and Go, CI compatibility check — one language for internal and public events / larger messages"],
  "All events use one envelope and JSON Schema files in `contracts/events/`; envelopes carry `api_version`; compatibility is checked in CI; this supersedes the Protobuf decision from the design discussion.",
  "Same schema documents internal topics and public webhooks; messages are larger (acceptable at target load); schema registry not needed."),
 ("010", "Kafka topics keyed by tenant_id", "Accepted", "NFR-FAIR-01, TLY-301",
  "Consumers need per-tenant ordering for state changes and a unit of fairness.",
  ["Key by aggregate id — even spread / no per-tenant ordering", "Key by tenant_id — per-tenant order, simple / hot partitions for whales"],
  "All topics are keyed by tenant_id with 24 partitions locally; whales are mitigated in the dispatcher by fair queues (ADR-011), not by Kafka partitioning.",
  "Order within a tenant; hot partitions possible — monitored by consumer lag per partition."),
 ("011", "Dispatcher: durable messages in Postgres, per-tenant fair queues in Redis", "Accepted", "NFR-FAIR-02, FR-WH-04, TLY-304, TLY-305",
  "Delivering directly from Kafka lets one slow endpoint block a partition and every tenant on it.",
  ["Deliver from the consumer loop — simple / head-of-line blocking", "Kafka retry topics — no DB / weak per-tenant fairness", "Persist messages, commit offset, schedule per tenant with WRR — fair, durable / two stores"],
  "The consumer persists one delivery message per matching endpoint, then commits the offset; a scheduler serves per-tenant Redis queues by weighted round-robin; Postgres is the source of truth, Redis is rebuildable.",
  "Slow tenants never block others; recovery rebuilds Redis from Postgres; operational complexity accepted for the learning goal."),
 ("012", "Webhook retries, circuit breaker, DLQ and auto-disable", "Accepted", "FR-WH-04, FR-WH-05, NFR-AVL-02, TLY-306",
  "Endpoints fail transiently and permanently; retrying too fast floods receivers, too slow loses freshness.",
  ["Fixed interval — simple / thundering herd", "Exponential backoff with full jitter + breaker + DLQ + disable — standard / more states"],
  "Schedule 30s, 2m, 8m, 30m, 2h, 6h, 12h, 24h with full jitter; breaker opens after 10 failures (HELD, probe 60 s); DEAD_LETTERED after 8 retries or 72 h; auto-disable after 50 consecutive failures or 410.",
  "Predictable receiver load; tenants see clear states; replay and bulk DLQ replay needed (TLY-307, TLY-810)."),
 ("013", "HMAC-SHA256 webhook signatures with timestamp and rotation", "Accepted", "FR-WH-02, FR-WH-03, TLY-305, TLY-312",
  "Receivers must verify origin and freshness; secrets must rotate without downtime.",
  ["Asymmetric signatures — no shared secret / heavier for receivers", "HMAC over timestamp + raw body with multiple v1 values during overlap — common, simple"],
  "`Tally-Signature: t=<ts>,v1=<hex>[,v1=…]`, 300 s tolerance, 24 h rotation overlap; golden vectors generated by script are normative (docs/03 §4).",
  "Easy receiver implementation; replay protection depends on receivers checking t; changes require new vectors first."),
 ("014", "Subscription lifecycle as an explicit state machine", "Accepted", "FR-SUB-02, TLY-501",
  "Status flags scattered in code produce impossible states (canceled and past due).",
  ["Boolean flags — quick / illegal combinations", "Explicit state machine with a transition table — testable / slightly more code"],
  "`SubscriptionStateMachine` owns all transitions (TRIALING, ACTIVE, PAST_DUE, CANCELED); illegal transitions raise `IllegalTransition` (409); each transition emits an event.",
  "Exhaustive table-driven tests; new states require an ADR amendment."),
 ("015", "Usage aggregation with event-time windows and exactly-once counting", "Accepted", "FR-MET-02, FR-MET-03, TLY-602",
  "Usage arrives late, duplicated and out of order; invoices must count each event exactly once.",
  ["Aggregate in Postgres at invoice time — simple / slow at scale, late events hard", "Stream processor with windows + dedup + deterministic rollup keys — scalable / more moving parts"],
  "The aggregator uses 5-minute tumbling windows by event time with 2-minute lateness, dedups by event id, checkpoints state to a compacted topic and emits rollups with deterministic `rollup_key` that the core upserts.",
  "Exactly-once effect end to end without Kafka transactions; period close decides what is billable."),
 ("016", "Single writer per data store", "Accepted", "NFR-MNT-01, TLY-304, TLY-603",
  "Shared databases couple deploys and hide ownership of invariants.",
  ["Workers write core tables — fewer hops / broken ownership", "Each store has one writer; others use events or APIs — clear ownership / eventual consistency"],
  "The core is the only writer of `tally`; the dispatcher of `dispatcher` and `wh:*`; the aggregator of its state topic. State the core needs from workers arrives as events.",
  "Invariants live next to their owner; some UI data is seconds stale."),
 ("017", "Payment processor behind a port with a simulator adapter", "Accepted", "FR-PAY-02, TLY-701",
  "Real processors cannot produce every failure on demand; vendor lock-in hurts tests and design.",
  ["Call Stripe SDK directly — fast start / untestable failures", "Port with Stripe test and simulator adapters sharing a contract test — testable / adapter upkeep"],
  "`PaymentProcessor` port with `StripeTestProcessor` and `SimulatorProcessor`; simulator behaviors keyed by token; unknown outcomes are first-class.",
  "Every failure path is testable offline; adapters must stay contract-compatible."),
 ("018", "OpenTelemetry end to end with a tenant label allow-list", "Accepted", "NFR-OBS-01..03, TLY-901",
  "Debugging async flows needs one trace across services; per-tenant metrics explode cardinality.",
  ["Logs only — cheap / no causality", "OTel traces + metrics + logs, tenant as span attribute, tenant label only on allow-listed metrics — full picture / discipline needed"],
  "W3C traceparent through HTTP and Kafka headers; `tenant.id` on every span and log; `tenant_id` metric label only on the allow-list enforced in CI.",
  "Incidents traceable across core and workers; cardinality bounded."),
 ("019", "Per-tenant rate limiting with Redis token buckets", "Accepted", "NFR-FAIR-03, TLY-111",
  "One tenant must not starve others on the shared pool.",
  ["Global limit — simple / unfair", "Per-tenant token bucket by plan with overrides — fair / Redis dependency"],
  "Token bucket per tenant and per surface (API, ingest) in Redis, limits from plan version or operator override; fail-open 60 s then in-memory at 2× plan.",
  "Fairness at the edge; Redis outage degrades gracefully; limits visible to tenants in Settings."),
 ("020", "Per-tenant envelope encryption and crypto-shredding", "Accepted", "NFR-SEC-05, FR-TEN-07, TLY-905",
  "Deleting a tenant from backups and replicas is impractical; PII must be unreadable after offboarding.",
  ["Delete rows only — backups still hold data", "Per-tenant DEK wrapped by a KEK; destroy DEK on offboarding — data unreadable everywhere / key management"],
  "Sensitive columns are encrypted with the tenant DEK; the DEK is stored wrapped by a KEK from the secret store; offboarding destroys the DEK after export.",
  "Offboarding is provable; lookups need keyed hashes (e.g. customer email); key rotation procedure required."),
 ("021", "Pool-to-silo migration by logical replication", "Proposed", "FR-OPS-03, FR-ADM-TEN-08, TLY-906",
  "Enterprise tenants may require dedicated storage without downtime.",
  ["Dump and restore with downtime — simple / downtime", "Logical replication filtered by tenant + routing switch — near-zero downtime / complex"],
  "Proposed: replicate tenant rows to a dedicated database, verify counts and ledger balances, pause writes ≤ 5 s, switch the tenant's datasource in the routing table; rollback within 15 minutes.",
  "Time-boxed in Sprint 15; if cut, this ADR stays Proposed with a design-only addendum."),
 ("022", "Separate operator console, API port and identity realm", "Accepted", "NFR-ADM-SEC-01, NFR-ADM-SEC-05, TLY-007, TLY-801",
  "Mixing operator powers into the tenant app makes every tenant-app bug an operator-level bug.",
  ["Admin pages in the tenant app — cheap / shared attack surface", "Separate app, origin, port (8081), filter chain and realm — isolation / more code"],
  "ops-web is a separate Next.js app on a VPN-only origin; `/ops/v1` runs on its own port and SecurityFilterChain accepting only operator-realm tokens with WebAuthn.",
  "Tenant tokens can never reach ops endpoints; duplicated UI primitives are shared as a package."),
 ("023", "Operator access to tenant data through the same RLS path with a reason", "Accepted", "NFR-ADM-SEC-08, NFR-ADM-AUD-01, TLY-801",
  "A BYPASSRLS operator role would make every operator query a potential cross-tenant leak.",
  ["BYPASSRLS operator role — easy / unsafe", "Set tenant context per request with a mandatory reason, audited — same guarantees as tenants / one tenant per request"],
  "Operator endpoints that read tenant data require `X-Access-Reason`, set the tenant context for that request, and write an audit entry in the same transaction. Cross-tenant aggregates come from read models and metrics, not raw tables.",
  "No RLS bypass anywhere; some fleet-wide views need dedicated read models."),
 ("024", "Impersonation via OAuth token exchange with an act claim", "Accepted", "FR-ADM-IMP-01..05, TLY-806",
  "Support needs to see what a tenant sees without sharing passwords, and tenants must see who did what.",
  ["Log in as the user — no attribution", "Token exchange (RFC 8693) with act claim, TTL = session, read-only by default — attributable / Keycloak configuration"],
  "Operators obtain a tenant-scoped token with `act.sub = operator`; READ_ONLY unless an approved request id is supplied; the tenant app shows a banner; tenants can list sessions.",
  "Full attribution in audit logs; write impersonation always needs four-eyes."),
 ("025", "Four-eyes approvals that execute stored payloads", "Accepted", "FR-ADM-GOV-01, FR-ADM-GOV-02, TLY-802",
  "High-risk operator actions need a second person, and the approved action must be exactly what was reviewed.",
  ["Approver re-submits the action — the payload can change", "Store payload + sha256 at request time; executor re-hashes and runs the stored payload — tamper-evident"],
  "Gated actions create `approval_requests` with payload and hash (24 h expiry); a different operator approves after step-up; `ApprovalExecutor` verifies the hash and executes the stored payload.",
  "Requester cannot approve; reviewers see exactly what runs; executor code paths must be idempotent."),
 ("026", "Hash-chained operator audit log", "Accepted", "NFR-ADM-AUD-02, NFR-ADM-AUD-03, TLY-801",
  "Audit logs are only useful if tampering is detectable.",
  ["Plain append-only table — deletions undetectable by DB superuser", "Hash chain with daily verification and alert — tamper-evident / sequential writes"],
  "Each entry stores `prev_hash` and `hash = sha256(prev_hash || canonical entry)`; UPDATE/DELETE revoked; a daily job verifies the chain and alerts on breaks.",
  "Tampering is detected, not prevented; writes are serialized on the sequence (acceptable at operator volumes)."),
 ("027", "Composite tenant foreign keys", "Accepted", "NFR-SEC-01, TLY-102",
  "RLS protects reads/writes, but a buggy insert could still link a row to another tenant's parent if the policy were ever misconfigured.",
  ["Single-column FKs — standard / cross-tenant references possible", "Composite FKs (tenant_id, x_id) → (tenant_id, id) — DB rejects cross-tenant links / wider indexes"],
  "Every intra-tenant reference is a composite FK; referenced tables carry `UNIQUE (tenant_id, id)`.",
  "Defense in depth independent of RLS; slightly larger indexes."),
 ("028", "Platform plans separate from the tenant catalog", "Accepted", "FR-TEN-02, FR-ADM-CFG-01, TLY-101, TLY-813",
  "What Tally charges tenants and what tenants charge their customers look similar but have different owners and lifecycles.",
  ["Reuse catalog tables for platform plans — less code / tenant-scoped RLS on platform data, confusion", "`tenancy.plan_versions` owned by operators, versioned and immutable — clear / some duplication"],
  "Platform plans live in `tenancy.plan_versions` (limits jsonb, immutable versions, migrations by operators); the tenant catalog lives in `catalog.*` under RLS.",
  "No mixing of operator and tenant data; plan changes are explicit migrations with dry runs."),
 ("029", "Runtime stack: Java 25 LTS, Spring Boot 4, Go 1.27", "Accepted", "Constraint in docs/02 §2.3, TLY-004, TLY-005",
  "The owner requires Java 25 and the latest Go. Java 25 is the current LTS; Go has no LTS and supports the two latest releases, of which 1.27 (August 2026) is the newest.",
  ["Java 21 + Spring Boot 3 — mature / older, Boot 3 OSS support ending", "Java 25 + Spring Boot 4 + Go 1.27 — current LTS, final ScopedValue, virtual threads without pinning, Go generic methods / newer ecosystem"],
  "Core on Java 25 with Spring Boot 4.x (Framework 7, Jackson 3, Spring Modulith); no preview features. Workers on Go 1.27. Exact library versions pinned in TLY-001/004/005 and upgraded by Renovate.",
  "Modern concurrency primitives available; some libraries may lag Jackson 3/Boot 4 (risk R-10); Go 1.28 upgrade planned when released."),
 ("030", "Monorepo with lanes and contract-first delivery", "Accepted", "NFR-MNT-04, TLY-001, TLY-003",
  "Parallel Claude Code sessions need conflict-free ownership and a stable interface to build against.",
  ["Polyrepo per service — hard isolation / cross-repo changes painful", "Monorepo, lanes own directories, contracts merged first, slices behind flags — parallel and coherent"],
  "One repository; lanes PLAT, CORE, WORK, WEB, OPSW own directories (CODEOWNERS); boundary changes start with a contracts PR merged on day 1; slices ship behind `FF_<SLICE>` flags.",
  "Frontends never wait for backends; the tech lead is the bottleneck by design (docs/07 §1)."),
 ("031", "Webhook delivery data served through a core proxy", "Accepted", "FR-WH-06, NFR-RT-01, TLY-307",
  "Delivery data lives in the dispatcher database (ADR-016), but tenant authentication and API conventions live in the core.",
  ["Expose dispatcher publicly with its own auth — duplicate auth logic", "Core reads dispatcher DB — breaks single writer/ownership", "Core `events` module proxies the dispatcher internal API — one auth path / an extra hop"],
  "Tenant and operator requests for deliveries, health, replay, fleet and SSE go through the core, which passes the tenant id from its context; the dispatcher filters by it and is reachable only on the internal network.",
  "Single auth and error model; +1 hop latency (acceptable); dispatcher API is an internal contract versioned with ops-openapi conventions."),
]
def slug(t): return re.sub(r"[^a-z0-9]+", "-", t.lower()).strip("-")[:60].rstrip("-")
for num, title, status, rel, ctx, opts, dec, cons in A:
    body = [f"# ADR-{num}: {title}", "", f"- **Status:** {status}", f"- **Date:** {DATE}", "- **Deciders:** Tech lead (Phan Cao Khai)", f"- **Related:** {rel}", "",
            "## Context", ctx, "", "## Options considered"] + [f"{i}. {o}" for i, o in enumerate(opts, 1)] + ["", "## Decision", dec, "", "## Consequences", cons, ""]
    (D / f"ADR-{num}-{slug(title)}.md").write_text("\n".join(body))
(ROOT / "scripts" / ".adr-index.md").write_text("\n".join(f"| [ADR-{n}](adr/ADR-{n}-{slug(t)}.md) | {t} | {s} |" for n, t, s, *_ in A))
print(len(A), "ADRs written")
