"""Single source for docs/06 and the sprint table in docs/07. Fields:
id, title, lane, pts, slice, deps, traces, sprint, story sentence, design artboard (or None), acceptance criteria."""
S = []
def st(i, title, lane, pts, slice_, deps, traces, sprint, as_a, design, ac):
    S.append(dict(id=f"TLY-{i}", title=title, lane=lane, pts=pts, slice=slice_, deps=deps, traces=traces, sprint=sprint, story=as_a, design=design, ac=ac))

# ---------------- E0 ----------------
st("001", "Monorepo scaffold, Makefile and CI skeleton", "PLAT", 5, "—", [], "NFR-MNT-01, NFR-MNT-04", 0,
   "As the tech lead, I want one repository with lane directories, a Makefile and CI, so that every lane builds and tests the same way from day one.", None,
   ["`make lint test` runs every lane's (empty) checks and exits 0 on a clean clone with only Docker, JDK 25, Go 1.27 and pnpm installed.",
    "GitHub Actions runs lint, test, contracts and gitleaks jobs per changed lane (path filters) and posts results on the PR.",
    "`.github/CODEOWNERS` and the PR template from docs/07 §8 are present; a PR without a story id in the title fails the `pr-title` check.",
    "Toolchain versions (JDK 25, Go 1.27, Node LTS, pnpm) are pinned in one file (`.tool-versions`) and CI reads them from there.",
    "`make docs-check` runs `scripts/validate_pack.py` and fails CI on any error."])
st("002", "Local stack with docker compose", "PLAT", 5, "—", ["TLY-001"], "NFR-COST-01, NFR-OBS-01", 0,
   "As a developer, I want `make up` to start Postgres, Kafka, Redis, Keycloak and the observability stack, so that every lane integrates locally.", None,
   ["`make up` starts Postgres (databases `tally`, `dispatcher`, `keycloak`), Kafka KRaft, Redis, Keycloak with realms `tally-tenants` and `tally-operators`, OTel collector, Prometheus, Tempo, Loki and Grafana; all health checks green within 120 s.",
    "Total resident memory of the stack is ≤ 16 GB, reported by `make up` (A-01).",
    "Kafka topics from docs/04 §7 are created with the documented partitions, retention and compaction.",
    "`make seed` loads `contracts/fixtures/tenants.json` into Keycloak and the core API once the core is running.",
    "`make down -v` removes all containers and volumes; `make up` afterwards starts from a clean state."])
st("003", "Contract pipeline and code generation", "PLAT", 5, "—", ["TLY-001"], "NFR-MNT-04, ADR-009", 0,
   "As the tech lead, I want contracts linted, diffed and turned into code for every lane, so that contract drift fails CI instead of production.", None,
   ["`make contracts` runs the three generators, Spectral lint (0 errors), oasdiff against `main` (breaking change fails unless the PR has label `breaking-approved`), JSON Schema compile and the webhook vector self-check.",
    "`make gen` produces Spring interfaces for core, Go types + sqlc models for workers, and openapi-typescript clients + MSW handlers for web and ops-web; generated folders are marked read-only in CODEOWNERS.",
    "Changing a response field in `scripts/gen_openapi.py` and running `make gen` produces a compile error in core until the handler is updated (demonstrated in the PR).",
    "CI fails if `make contracts` leaves a diff in `contracts/` (generated files must be committed)."])
st("004", "Core skeleton: Java 25, Spring Boot 4, Spring Modulith", "CORE", 5, "—", ["TLY-001", "TLY-003"], "NFR-MNT-01, NFR-MNT-03, NFR-COR-04", 0,
   "As the CORE lane, I want a modular monolith skeleton with enforced boundaries, so that modules stay independent as they grow.", None,
   ["Gradle build with Java 25 toolchain, Spring Boot 4.x, Spring Modulith and the eleven module packages from core/CLAUDE.md; exact versions pinned in `gradle/libs.versions.toml`.",
    "`./gradlew archTest` runs Spring Modulith `verify()` and ArchUnit rules (domain has no framework imports; no `double`/`float`/`BigDecimal` in `..money..` and `..ledger..`; no field injection); a deliberate violation in a test fixture fails the build.",
    "Flyway applies `V001__baseline_roles_schemas.sql`; `PostgresKafkaIT` base class starts Testcontainers and a sample repository test passes.",
    "Ports 8080 (`/v1`), 8081 (`/ops/v1`) and 8082 (actuator) serve `GET /v1/health` style probes; virtual threads enabled; JSON logs include `service` and `trace_id`.",
    "The OpenAPI request/response validation filter is active in tests and rejects a response that violates `contracts/openapi.yaml`."])
st("005", "Workers skeleton: Go 1.27 dispatcher and aggregator", "WORK", 3, "—", ["TLY-001", "TLY-003"], "NFR-MNT-01", 0,
   "As the WORK lane, I want two runnable Go binaries with config, telemetry and graceful shutdown, so that delivery and aggregation stories start from a sound base.", None,
   ["`go build ./...` builds `cmd/dispatcher` and `cmd/aggregator` with `go 1.27` in go.mod; golangci-lint config from workers/CLAUDE.md passes.",
    "Both binaries load typed env config and exit non-zero with a clear message when a required variable is missing.",
    "SIGTERM stops intake and exits within 30 s; a `goleak` test proves no goroutine outlives shutdown.",
    "depguard forbids `internal/*/domain`-style packages from importing pgx, franz-go or net/http; a violating import fails lint."])
st("006", "Web shell, design tokens and mock mode", "WEB", 5, "—", ["TLY-001", "TLY-003"], "NFR-FE-01, NFR-FE-02, NFR-FE-05", 0,
   "As a tenant user, I want a consistent app shell, so that every screen feels like one product.", "Main / Home (shell)",
   ["The shell renders the full sidebar (Home, Customers, Subscriptions, Invoices, Payments, Usage, Products, Developers group, Settings) on every route, with the active item and topbar (search, test-mode toggle, bell, avatar) matching the canvas.",
    "Design tokens (colors, type scale with Geist + Instrument Serif, spacing, radii) and motion tokens from docs/02 §7.8 live in one module; lint forbids raw hex colors and raw durations in components.",
    "`NEXT_PUBLIC_API_MODE=mock` serves every route from generated MSW handlers; `live` goes through the BFF.",
    "With `prefers-reduced-motion: reduce`, no transform animations run (Playwright check).",
    "Lighthouse on the empty Home shell: performance ≥ 90, accessibility 100."])
st("007", "Operator console shell", "OPSW", 3, "—", ["TLY-001", "TLY-003"], "NFR-ADM-UX-02, NFR-ADM-SEC-09", 0,
   "As an operator, I want a distinct dark, dense console shell, so that I never confuse it with the tenant app.", "Admin Overview (shell)",
   ["Separate Next.js app on port 3100 with the dark compact theme and the 14-item ops sidebar from the canvas.",
    "A non-dismissible environment badge (PRODUCTION red / STAGING amber) and a session timer render on every page.",
    "Strict CSP (no third-party scripts, `frame-ancestors 'none'`) is served and verified by a Playwright header check.",
    "Mock mode works from `contracts/ops-openapi.yaml` MSW handlers."])

# ---------------- E1 ----------------
st("101", "Tenant provisioning and plan versions", "CORE", 5, "S1", ["TLY-004"], "FR-TEN-01, FR-TEN-02, ADR-028", 1,
   "As an operator, I want to create a tenant with a plan version and isolation tier, so that a new business can start using Tally.", None,
   ["`POST /ops/v1/tenants` with an Idempotency-Key creates the tenant, owner membership invitation, invoice number sequence and default ledger accounts in one transaction; a repeat with the same key returns the same tenant.",
    "The tenant gets `isolation_tier = POOL` unless the plan version's limits specify SILO; the value is returned by the API.",
    "Plan versions are seeded (`starter v1`, `growth v1`, `scale v1`) and immutable; a tenant references exactly one version.",
    "A `tenant.created` audit entry records the operator as actor.",
    "Creating a tenant with an unknown `plan_code` returns 400 `VALIDATION_FAILED` with `param = plan_code`."])
st("102", "Tenant context and row-level security", "CORE", 8, "—", ["TLY-004"], "NFR-SEC-01, NFR-SEC-02, ADR-002, ADR-003, ADR-027", 1,
   "As the platform, I want every query scoped to the tenant from the credential, so that no tenant can ever read or write another tenant's data.", None,
   ["`TenantFilter` resolves the tenant from the JWT `tenant_id` claim or the API key and binds a `ScopedValue<TenantContext>`; any `tenant_id` in headers, query or body is ignored.",
    "Every transaction runs `SET LOCAL app.tenant_id` before the first statement; `RlsCoverageIT` asserts that every table with a `tenant_id` column has RLS enabled and forced.",
    "With the context unset, a repository query returns zero rows (fails closed) and logs WARN `tenant_context_missing`.",
    "A composite-FK test shows that inserting a subscription for another tenant's customer id fails with a FK violation even if RLS were disabled.",
    "An ArchUnit rule fails the build if a class in `..adapter.out..` executes SQL outside a transaction for a tenant table."])
st("103", "Identity: resource server and /v1/me", "CORE", 5, "S1", ["TLY-004"], "FR-TEN-05, NFR-SEC-02", 1,
   "As a tenant user, I want my identity and memberships resolved from my token, so that the dashboard knows who I am and which tenant is active.", None,
   ["Core validates JWTs from realm `tally-tenants` (issuer, audience, signature, expiry); invalid tokens get 401 `UNAUTHENTICATED`.",
    "`GET /v1/me` returns the user, the active tenant (from the `tenant_id` claim) with role, and all memberships.",
    "A token whose `tenant_id` is not among the user's active memberships is rejected with 401.",
    "Role-based checks use a single `Permission` matrix (docs/02 §7.1) shared by controllers; a VIEWER calling a write endpoint gets 403 `FORBIDDEN_SCOPE`."])
st("104", "BFF login, session and tenant switcher", "WEB", 5, "S1", ["TLY-006"], "FR-TEN-05, NFR-FE-04", 1,
   "As a tenant user, I want to sign in once and switch between my tenants, so that I can work across businesses safely.", "Main / Home (topbar)",
   ["`/auth/login` → Keycloak → `/auth/callback` sets an httpOnly, Secure, SameSite=Lax encrypted session cookie; no token is readable from browser JavaScript.",
    "The tenant switcher lists memberships from `GET /v1/me`; choosing one calls `/auth/switch-tenant`, which performs token exchange and reloads into the new tenant.",
    "On switch, all TanStack Query caches and client stores are cleared before the first render of the new tenant (unit test asserts empty cache).",
    "Session idle timeout 30 min, absolute 12 h; expiry redirects to login preserving the target URL.",
    "Works in mock mode with two fixture tenants."])
st("105", "API keys: create once, hash, scope, revoke", "CORE", 5, "S2", ["TLY-102", "TLY-110"], "FR-TEN-04, FR-KEY-01, FR-KEY-02, NFR-SEC-04", 2,
   "As a tenant developer, I want scoped API keys, so that my backend can call Tally with least privilege.", None,
   ["`POST /v1/api_keys` returns the secret exactly once; only prefix, last4 and an Argon2id hash are stored; a log scan test finds no secret in logs.",
    "Requests with a key resolve tenant, mode (LIVE/TEST) and scopes; a missing scope returns 403 `FORBIDDEN_SCOPE`.",
    "`POST /v1/api_keys/{id}/revoke` makes the key fail on every core instance within 5 s (cache TTL 5 s, integration test with two app instances).",
    "`last_used_at` updates at most once per minute per key (no write per request).",
    "A TEST key cannot read or write LIVE-mode objects and vice versa."])
st("106", "API keys screen", "WEB", 3, "S2", ["TLY-006"], "FR-KEY-01", 2,
   "As a tenant developer, I want to manage keys in the dashboard, so that I can rotate them without support.", "ApiKeys",
   ["The list shows name, mode, prefix•••last4, scopes, created and last used; secrets never appear in the list.",
    "Create opens the modal; after success the secret is shown once with copy and a required 'I have stored it' confirmation before close.",
    "Revoke asks for confirmation naming the key and shows the row as revoked without a page reload.",
    "Empty, loading and error states match the canvas; keyboard-only flow passes axe."])
st("107", "Team members and invitations", "CORE", 5, "S3", ["TLY-103"], "FR-SET-01", 3,
   "As a tenant admin, I want to invite teammates with roles, so that the right people can work in Tally.", None,
   ["`POST /v1/team/invitations` creates an invitation that expires in 7 days and emails a one-time link (email sender port, fake in tests).",
    "Accepting creates the membership with the invited role; an expired or reused link returns 410.",
    "`PATCH /v1/team/members/{userId}` changes roles; the last OWNER cannot be demoted or removed (409 `INVALID_STATE`).",
    "Only OWNER/ADMIN can manage the team; others get 403.",
    "Each change writes an audit entry with actor and target."])
st("108", "Settings screen: team, branding, plan and limits", "WEB", 5, "S3", ["TLY-006"], "FR-SET-01, FR-SET-02, FR-SET-03", 4,
   "As a tenant admin, I want one settings screen for team, branding and plan, so that I can manage my account in minutes.", "Settings",
   ["Team tab lists members and pending invitations with role selects and invite form; role changes are optimistic with rollback on error.",
    "Branding tab previews the accent color and logo live on a sample invoice before saving; invalid hex is rejected inline.",
    "Plan tab shows plan, version and each limit with a usage bar; bars ≥ 80 % are amber, ≥ 100 % red with label (not color only).",
    "Saving branding sends `If-Match`; a 412 shows 'Someone else changed this' with a reload action."])
st("109", "Branding and account plan endpoints", "CORE", 3, "S3", ["TLY-102"], "FR-SET-02, FR-SET-03", 3,
   "As a tenant admin, I want to set branding and see my plan limits, so that invoices look like my business and I know my headroom.", None,
   ["`GET/PATCH /v1/settings/branding` with ETag/If-Match; accent must match `^#[0-9A-Fa-f]{6}$`.",
    "`POST /v1/settings/branding/logo` accepts SVG or PNG ≤ 512 KB; SVGs are sanitized (no scripts, no external refs).",
    "`GET /v1/account/plan` returns limits from the plan version and current usage for each (customers, API rpm, webhook endpoints, usage events/month).",
    "Invoice PDF rendering reads branding (verified in TLY-505)."])
st("110", "Idempotency filter and tenant audit log", "CORE", 5, "—", ["TLY-102"], "NFR-COR-03, FR-OPS-02, ADR-006", 2,
   "As a tenant developer, I want retries to be safe, so that a network error never creates a duplicate object or charge.", None,
   ["For endpoints marked idempotent in the spec, a missing `Idempotency-Key` returns 400.",
    "Same key + same request hash returns the stored status and body without re-executing; the response carries `Idempotent-Replayed: true`.",
    "Same key + different hash returns 422 `IDEMPOTENCY_KEY_REUSED`; a concurrent duplicate while the first is running returns 409 `IDEMPOTENCY_IN_PROGRESS`.",
    "Keys expire after 24 h (cleanup job); keys are scoped per tenant.",
    "Every state-changing use case writes `kernel.audit_log` (actor type, actor id, on_behalf_of, action, target) in the same transaction."])
st("111", "Per-tenant rate limiting", "CORE", 5, "—", ["TLY-102", "TLY-101"], "NFR-FAIR-03, NFR-FAIR-01", 4,
   "As the platform, I want each tenant limited to its plan's rate, so that one tenant cannot degrade the others.", None,
   ["A Redis token bucket per tenant uses `rate_limit_rpm` from the plan version, or an active `ops.rate_limit_overrides` row.",
    "Exceeding the limit returns 429 `RATE_LIMITED` with `Retry-After` and `RateLimit-*` headers; other tenants' requests are unaffected (integration test with two tenants).",
    "If Redis is unavailable the limiter fails open for ≤ 60 s with a WARN log and metric, then fails closed at 2× the plan rate using an in-memory limiter.",
    "Usage ingest has its own bucket so API reads are not starved by ingest bursts."])

# ---------------- E2 ----------------
st("201", "Money value object", "CORE", 3, "—", ["TLY-004"], "NFR-COR-04, ADR-004", 1,
   "As a CORE developer, I want one Money type, so that amounts cannot be mixed, rounded or overflowed by accident.", None,
   ["`Money(long minor, Currency currency)` with `plus`, `minus`, `times(long)`, `negate`, `isZero`; arithmetic uses `Math.*Exact` and throws on overflow.",
    "Operations across currencies throw `CurrencyMismatch`.",
    "Jackson 3 module serializes to `{amount, currency}` (lowercase) and rejects decimals on input with 400.",
    "`Money.allocate(ratios)` splits without losing a minor unit (property test: sum of parts equals the whole for 10,000 random inputs)."])
st("202", "Double-entry ledger with enforced balance", "CORE", 8, "—", ["TLY-201", "TLY-102"], "FR-LED-01, FR-LED-02, FR-LED-04, NFR-COR-01, NFR-PER-04, ADR-005", 2,
   "As the platform, I want every money movement recorded as a balanced journal entry, so that the books are always correct.", None,
   ["`LedgerService.post(JournalEntry)` persists an entry with ≥ 2 postings; the builder rejects entries that do not sum to zero per currency.",
    "The deferred database trigger rejects an unbalanced entry at commit even when inserted with raw SQL (integration test).",
    "Postings and entries cannot be updated or deleted by the app role (grant test); `reverse(entryId)` writes a mirror entry with `reverses_id`.",
    "Each entry stores `source_type` and `source_id` (invoice, payment, refund, credit_note).",
    "jqwik property test: 10⁶ random valid postings keep every account balance equal to the sum of its postings and the trial balance at zero.",
    "Throughput test: 1,000 entries/s sustained for 60 s on the local stack with 0 violations."])
st("203", "Balances as of a point in time", "CORE", 3, "—", ["TLY-202"], "FR-LED-03", 2,
   "As a finance user, I want account balances as of any time, so that I can answer 'what was owed on date X'.", None,
   ["`LedgerQueries.balance(account, asOf)` returns the signed balance from postings up to `asOf` using the `postings_account` index.",
    "Balances for a chart of accounts are returned in one query (no N+1, asserted by statement count).",
    "p95 < 50 ms for an account with 100k postings (JMH or integration timing).",
    "Results match the property-test oracle from TLY-202."])

# ---------------- E3 ----------------
st("301", "Transactional outbox and relay", "CORE", 5, "—", ["TLY-102", "TLY-002"], "NFR-COR-02, NFR-PER-06, NFR-AVL-03, ADR-008, ADR-010", 2,
   "As the platform, I want events written in the same transaction as state changes and relayed to Kafka, so that no event is lost or invented.", None,
   ["`OutboxPort.publish(event)` inserts into `kernel.outbox_events` in the caller's transaction; a rolled-back transaction leaves no outbox row.",
    "The relay claims batches of 500 with `FOR UPDATE SKIP LOCKED`, produces with key = tenant_id and headers `event-type`, `tenant-id`, `schema-version`, `traceparent`, then marks rows published.",
    "Killing the relay between produce and mark results in re-publication of the same event ids, never loss (integration test).",
    "With Kafka stopped, API writes still succeed; after restart the backlog drains and `tally_outbox_unpublished` returns to 0.",
    "Relay lag p99 < 1 s at 200 writes/s (metric `tally_outbox_lag_seconds`)."])
st("302", "Event log and Events API", "CORE", 5, "S5", ["TLY-301"], "FR-EVT-01, ADR-009", 3,
   "As a tenant developer, I want to browse the events Tally emitted, so that I can debug my integration.", None,
   ["Every outbox event is also stored in `events.events` (same transaction) with a 30-day retention job.",
    "`GET /v1/events` filters by `type` and paginates newest first; `GET /v1/events/{id}` returns the payload and per-endpoint delivery status (from the dispatcher proxy).",
    "Payloads validate against `contracts/events/*.schema.json` in a contract test for every event type produced.",
    "Another tenant's event id returns 404."])
st("303", "Webhook endpoints, secrets and SSRF validation", "CORE", 5, "S4", ["TLY-301", "TLY-110"], "FR-WH-01, FR-WH-03, FR-WH-05, FR-WH-07", 3,
   "As a tenant developer, I want to register webhook endpoints, so that my systems react to billing events.", None,
   ["`POST /v1/webhook_endpoints` validates HTTPS and resolves the host; URLs resolving to private, loopback, link-local or metadata ranges are rejected with 400 `VALIDATION_FAILED`.",
    "The secret (256-bit) is returned once; `rotate_secret` creates a new secret and keeps the old one valid for 24 h.",
    "Every create/update/delete/rotate emits `webhook_endpoint.updated|deleted` on the control topic with encrypted secrets.",
    "Consuming `webhook_endpoint.auto_disabled` sets status DISABLED, creates an attention item and emails the tenant; `enable` emits an update the dispatcher uses to send a test event.",
    "Plan limit on endpoint count enforced (409 with limit in detail)."])
st("304", "Dispatcher consumer and delivery messages", "WORK", 5, "—", ["TLY-005", "TLY-003"], "FR-WH-04, NFR-COR-03, ADR-011", 3,
   "As the platform, I want every event turned into durable delivery messages before offsets are committed, so that a crash never loses a webhook.", None,
   ["The consumer maintains `endpoint_projection` from control events and creates one `delivery_messages` row per matching endpoint in one transaction.",
    "The Kafka offset is committed only after that transaction commits; killing the process after persist and before commit creates no duplicate rows (unique index).",
    "Events for tenants with no matching endpoint are acknowledged without rows.",
    "Consumer lag is exported as `tally_dispatcher_consumer_lag`; the consumer never waits on HTTP delivery."])
st("305", "Fair scheduler, signing and SSRF-safe delivery", "WORK", 8, "—", ["TLY-304"], "NFR-FAIR-02, NFR-PER-05, FR-WH-02, NFR-SEC-06, ADR-011, ADR-013", 4,
   "As a tenant, I want my webhooks delivered promptly even when another tenant's endpoint is down, so that my integration stays real-time.", None,
   ["Due messages are queued per tenant in Redis and served weighted round-robin (weight from plan); ≤ 8 in flight per endpoint and 256 total.",
    "Each attempt is signed per docs/03 §4; the signer passes every vector in `contracts/webhooks/signature-vectors.json`.",
    "The dialer blocks private/loopback/link-local/metadata IPs after DNS resolution, including a DNS-rebinding test (first resolve public, second private).",
    "Fairness test: tenant A has a dead endpoint and 100k backlog; tenants B–E keep p95 time-to-first-attempt within 10 % of baseline (NFR-FAIR-02).",
    "Healthy-endpoint p95 from commit to first attempt < 5 s end to end (NFR-PER-05).",
    "Timing (dns, connect, tls, wait, download) is recorded per attempt."])
st("306", "Retries, circuit breaker, DLQ and auto-disable", "WORK", 5, "—", ["TLY-305"], "FR-WH-04, FR-WH-05, NFR-AVL-02, ADR-012", 4,
   "As a tenant, I want failed webhooks retried sensibly and parked when my endpoint is broken, so that nothing is lost and my endpoint is not flooded.", None,
   ["Failures follow the schedule in docs/03 §7 with full jitter; `Retry-After` is honored up to 1 h.",
    "After 8 retries or 72 h the message becomes DEAD_LETTERED with the last error.",
    "10 consecutive failures open the circuit (new messages HELD, probe every 60 s); a success closes it and drains at ≤ 20/s.",
    "50 consecutive failures (or a 410) disable the endpoint and publish `webhook_endpoint.auto_disabled`.",
    "A fake-clock test walks one message through every state without sleeping."])
st("307", "Deliveries API, replay and live stream", "WORK", 5, "S4", ["TLY-304"], "FR-WH-06, NFR-RT-01, ADR-031", 5,
   "As a tenant developer, I want to inspect and replay deliveries and watch them live, so that I can fix integration issues fast.", None,
   ["Dispatcher internal API serves deliveries (filters: endpoint, status), a delivery with attempts/headers/timing, 24 hourly health buckets per endpoint, and replay; core `events` module proxies them at the `/v1` paths with tenant auth.",
    "Replay creates a new message with `replay_of`, same event id, and returns 202; replay is idempotent per Idempotency-Key.",
    "`GET /v1/streams/webhook_deliveries` streams `delivery.created`, `delivery.updated`, `endpoint.health` and a 15 s heartbeat; reconnect with `Last-Event-ID` replays ≤ 5 min.",
    "A tenant can never see another tenant's deliveries through the proxy (proxy passes tenant id from the core context; dispatcher filters by it; test with forged ids).",
    "Responses validate against `contracts/openapi.yaml`."])
st("308", "Webhook monitor screen", "WEB", 8, "S4", ["TLY-006"], "FR-WH-06, NFR-RT-01, NFR-FE-01", 5,
   "As a tenant developer, I want a live webhook monitor, so that I can see delivery health at a glance and act on failures.", "Webhooks",
   ["Endpoint cards show status, 24-hour health bars (grow on load) and success rate; the live feed prepends rows with a slide-in without shifting the scroll position.",
    "Selecting a delivery opens the detail panel with request headers, response, attempt list and the timing waterfall.",
    "Replay and pause/resume actions send an Idempotency-Key and show pending then result states; failures show the problem detail.",
    "SSE updates are batched per animation frame; the stream reconnects with backoff and shows a 'reconnecting' pill after 3 s.",
    "Reduced motion replaces slide/grow with fades; status uses color + icon + label."])
st("309", "Endpoint management UI", "WEB", 3, "S4", ["TLY-006"], "FR-WH-01, FR-WH-03, FR-WH-05", 5,
   "As a tenant developer, I want to add endpoints, rotate secrets and re-enable disabled endpoints, so that I control my integration.", "Webhooks (endpoint drawer)",
   ["Add endpoint form validates URL and event types; server SSRF errors appear inline on the URL field.",
    "The signing secret is revealed once after create/rotate with copy and a 24-hour overlap note.",
    "Disabled endpoints show the reason and a 'Send test & re-enable' action.",
    "Delete requires typing the endpoint host."])
st("310", "Events and logs screen", "WEB", 5, "S5", ["TLY-006"], "FR-EVT-01, FR-EVT-02", 5,
   "As a tenant developer, I want to search events and API requests, so that I can trace what happened.", "Events",
   ["Events tab lists type, id, time and delivery summary; selecting one shows the JSON payload with copy and per-endpoint status.",
    "Requests tab lists method, path, status, latency and key name with a status filter; 4xx/5xx rows are visually distinct with a label.",
    "Filters are reflected in the URL so views can be shared.",
    "Long lists are virtualized and keep 60 fps scrolling over 10,000 rows (Playwright trace)."])
st("311", "Request log pipeline and API", "CORE", 3, "S5", ["TLY-002", "TLY-102"], "FR-EVT-02, NFR-LOG-01", 4,
   "As a tenant developer, I want my API request log for 14 days, so that I can debug failed calls.", None,
   ["Each `/v1` request emits one structured access record (tenant, key name, method, route template, status, latency, request id) to the OTel logs pipeline; bodies are never logged.",
    "`GET /v1/request_logs` queries Loki with a mandatory tenant filter added server-side; retention 14 days.",
    "Records never go to the billing Postgres (NFR-LOG-01).",
    "Query p95 < 500 ms for a 24 h window at 1M records locally."])
st("312", "Webhook signing golden vectors and verification guide", "PLAT", 2, "—", ["TLY-003"], "FR-WH-02, ADR-013", 1,
   "As a tenant developer, I want verified examples of signature checking, so that my receiver implementation is correct the first time.", None,
   ["`scripts/gen_webhook_vectors.py` generates the five vectors in docs/03 §4 and self-verifies them in `make contracts`.",
    "Verification snippets for Node, Python, Java and Go in `docs/guides/verify-webhooks.md` pass all vectors in a CI job.",
    "Changing the signing rule without regenerating vectors fails CI."])

# ---------------- E4 ----------------
st("401", "Products and immutable price versions", "CORE", 5, "S6", ["TLY-102", "TLY-110"], "FR-CAT-01, FR-CAT-02, FR-CAT-03, FR-CAT-04", 3,
   "As a tenant admin, I want products with versioned prices, so that price changes never alter what existing customers pay.", None,
   ["Create products (SEAT, FLAT, METERED) and prices (PER_UNIT, FLAT, GRADUATED with tiers, MONTH/YEAR, one currency).",
    "`POST /v1/products/{id}/prices` creates version n+1; the previous version becomes LEGACY; a trigger rejects UPDATE of amount, model, currency or tiers.",
    "`GET /v1/products/{id}/prices` returns `subscription_count` per version.",
    "Archiving a price with active subscriptions returns 409 `INVALID_STATE` with the count.",
    "Graduated tiers must be ascending with exactly one open-ended last tier (400 otherwise)."])
st("402", "Products and pricing screen", "WEB", 5, "S6", ["TLY-006"], "FR-CAT-01, FR-CAT-04", 5,
   "As a tenant admin, I want to see and edit my pricing safely, so that I understand who is on which version.", "Products",
   ["Product cards show kind, current price and subscriptions; the versions timeline shows CURRENT/LEGACY/ARCHIVED with counts.",
    "Editing a price explains that a new version is created and shows how many subscriptions stay on the old one before confirm.",
    "Graduated tier editor validates ascending boundaries inline.",
    "Archive action is disabled with a tooltip when subscriptions remain."])
st("403", "Customers API and timeline", "CORE", 5, "S7", ["TLY-102", "TLY-110"], "FR-CUS-01, FR-CUS-03", 6,
   "As a tenant, I want to manage my customers, so that I can bill them.", None,
   ["Create/update/get/list customers; email stored encrypted with a keyed hash; duplicate email within a tenant returns 409, across tenants is allowed.",
    "`GET /v1/customers?q=` searches name and exact email (via hash); `sort=-mrr` supported; p95 < 100 ms over 50k customers.",
    "`PATCH` requires If-Match and returns 412 on a stale ETag.",
    "`GET /v1/customers/{id}/timeline` merges subscription, invoice and payment events newest first.",
    "`customer.created|updated` events are published via the outbox."])
st("404", "Payment method setup via processor tokens", "CORE", 3, "S7", ["TLY-403"], "FR-CUS-02, NFR-SEC-03", 6,
   "As a tenant, I want customers' cards stored only by the processor, so that I stay out of PCI scope.", None,
   ["`POST /v1/customers/{id}/payment_method_setups` returns a processor setup token (simulator or Stripe test); Tally never receives card numbers.",
    "Completing setup stores token, brand, last4 and expiry only.",
    "Detach marks `detached_at`; a detached method cannot be charged (409).",
    "A test sends a request containing a 16-digit PAN-like string to every customer endpoint and asserts 400 and no persistence."])
st("405", "Customers list and Customer 360 screens", "WEB", 5, "S7", ["TLY-006"], "FR-CUS-01, FR-CUS-03", 6,
   "As a tenant admin, I want to find a customer and see everything about them on one page, so that I can answer questions quickly.", "CustomersList, Customers",
   ["List with search, status filter, MRR sort and virtualized rows; row click opens Customer 360.",
    "Customer 360 shows profile, MRR, open balance, subscriptions, invoices, payment methods and the timeline, each section with its own loading/empty/error state.",
    "Editing profile uses If-Match; a 412 shows a non-destructive reload prompt.",
    "Emails in the list are shown in full to tenant users (their own data) but never logged by the client."])

# ---------------- E5 ----------------
st("501", "Subscription lifecycle state machine", "CORE", 8, "S8", ["TLY-401", "TLY-403"], "FR-SUB-01, FR-SUB-02, FR-SUB-04, ADR-014", 6,
   "As a tenant, I want subscriptions that move only through legal states, so that billing behaves predictably.", None,
   ["Create with items and optional trial (0–90 days); status TRIALING or ACTIVE; period bounds computed from the price interval in the tenant time zone.",
    "`SubscriptionStateMachine` allows only TRIALING→ACTIVE, ACTIVE→PAST_DUE, PAST_DUE→ACTIVE, any→CANCELED; illegal transitions return 409 (table-driven test of all 16 pairs).",
    "Cancel NOW ends the subscription and creates a final prorated credit per policy; PERIOD_END sets `cancel_at_period_end`.",
    "Renewal job advances periods for due subscriptions idempotently (job key = subscription + period).",
    "Events `subscription.created|renewed|updated|canceled|trial_ending` are published; trial_ending fires 3 days before trial end."])
st("502", "Pricing engine, preview and proration", "CORE", 5, "S8", ["TLY-401"], "FR-SUB-03, FR-SUB-06", 6,
   "As a tenant admin, I want to preview the exact charge before creating or changing a subscription, so that there are no surprises.", None,
   ["`POST /v1/subscriptions/preview` returns lines, recurring total, due today and a plain-language explanation, with no writes (asserted by statement log).",
    "Preview and the real invoice use the same `PricingEngine`; a property test shows preview total = first invoice total for random item sets.",
    "Mid-cycle quantity/price changes produce proration lines by seconds remaining, rounded HALF_EVEN once per line.",
    "Graduated pricing computes each tier separately (worked example in the test: 12,000 units over tiers 0–10k @1¢, >10k @0.8¢ = $116.00).",
    "`PATCH /v1/subscriptions/{id}` requires If-Match and applies the same proration."])
st("503", "Subscription builder and subscriptions list", "WEB", 8, "S8", ["TLY-006"], "FR-SUB-01, FR-SUB-06", 7,
   "As a tenant admin, I want a guided builder with a live price preview, so that I can create subscriptions correctly the first time.", "SubscriptionBuilder, SubscriptionsList",
   ["Builder steps: customer → items → trial → review; step transitions animate per tokens; back keeps entered data.",
    "The preview panel calls the preview endpoint (debounced 300 ms) and shows lines, due today and the explanation; stale previews are dimmed while loading.",
    "Create sends one Idempotency-Key per review-screen intent; double click creates one subscription (Playwright test).",
    "List supports plan, status and 'renews this week' filters with counts, and cancel (now / period end) with confirmation.",
    "The flow is keyboard-complete and passes axe."])
st("504", "Billing run and draft invoices", "CORE", 8, "S9", ["TLY-501", "TLY-502"], "FR-INV-01, FR-INV-02", 7,
   "As a tenant, I want invoices drafted automatically at period end, so that I bill every customer on time.", None,
   ["The billing-run job selects due subscriptions in batches with `SKIP LOCKED` and creates one DRAFT invoice per subscription period (idempotent key = subscription + period).",
    "Lines come from subscription items and closed usage rollups (metered lines reference `usage_rollup_id`).",
    "Drafts can be edited (lines add/remove, due date, memo) with If-Match; once not DRAFT, edits return 409 and the DB trigger blocks line changes.",
    "`GET /v1/invoices/summary` returns outstanding, overdue and paid-this-month from read models.",
    "Drafts auto-finalize after 1 hour unless the tenant disabled auto-finalize (setting)."])
st("505", "Finalize, void and credit notes with ledger postings", "CORE", 5, "S9", ["TLY-504", "TLY-202"], "FR-INV-03, FR-INV-04, FR-INV-05, FR-INV-06", 7,
   "As a tenant, I want finalized invoices numbered without gaps and reflected in the ledger, so that my books and my customers' records agree.", None,
   ["Finalize in one transaction: lock the tenant sequence, assign `<prefix>-<n>`, post Dr Accounts receivable / Cr Revenue, insert `invoice.finalized` into the outbox.",
    "50 concurrent finalizes for one tenant yield 50 distinct consecutive numbers and no gaps even when 5 of them roll back after numbering (numbers assigned last).",
    "Void posts the reversing entry (`reverses_id`), sets VOID and emits `invoice.voided`; voiding a PAID invoice returns 409.",
    "Credit notes reduce amount due and post Dr Contra-revenue / Cr Accounts receivable.",
    "The PDF renders with tenant branding; its totals equal the ledger entry (test compares)."])
st("506", "Invoices list and invoice detail screens", "WEB", 8, "S9", ["TLY-006"], "FR-INV-02, FR-INV-07", 8,
   "As a finance user, I want to review, finalize and chase invoices, so that I get paid.", "InvoicesList, InvoiceDetail",
   ["List tabs (All, Draft, Open, Overdue, Paid) with counts and summary tiles; overdue rows show days overdue with an icon and label.",
    "Detail shows lines, totals, customer, history and the PDF preview; draft lines are editable inline, finalized invoices hide all edit controls.",
    "Finalize plays the seal animation after the 200 response (never before) and shows the assigned number.",
    "Bulk select + 'Send reminders' reports accepted and skipped with reasons.",
    "Money values never animate except the seal; reduced motion shows a static stamp."])
st("507", "Invoice reminders", "CORE", 3, "S9", ["TLY-504"], "FR-INV-07", 7,
   "As a finance user, I want to send reminders in bulk, so that overdue invoices get paid.", None,
   ["`POST /v1/invoices/reminders` accepts ≤ 100 ids and returns 202 with accepted and skipped (reasons: NOT_OPEN, REMINDED_WITHIN_24H, NOT_FOUND).",
    "Reminders are sent asynchronously through the email port with tenant branding; each writes `invoice_reminders`.",
    "The same invoice is never reminded twice within 24 h.",
    "Idempotency-Key replays return the original result."])
st("508", "Test clocks", "CORE", 3, "—", ["TLY-501", "TLY-504"], "FR-SUB-05", 11,
   "As a tenant developer, I want to fast-forward time in test mode, so that I can test renewals and dunning without waiting.", None,
   ["Test clocks can be created only with TEST keys; LIVE returns 403.",
    "Subscriptions attached to a clock use its frozen time for all period calculations.",
    "`advance` runs due renewals, billing runs and dunning steps for attached subscriptions up to the new time, in order, idempotently.",
    "Advancing backwards returns 400."])

# ---------------- E6 ----------------
st("601", "Usage ingest API", "CORE", 5, "S10", ["TLY-102", "TLY-301"], "FR-MET-01, FR-MET-02, NFR-PER-03, NFR-COR-03", 7,
   "As a tenant developer, I want to send usage in batches, so that metered billing reflects real consumption.", None,
   ["`POST /v1/usage_events` accepts 1–1,000 events, validates meter keys and customers, and returns 202 with accepted and duplicates counts.",
    "Duplicate `event_id` (same tenant) is counted in `duplicates` and not stored twice (`usage_event_ids` PK).",
    "Each accepted event produces a `usage.recorded` outbox message on `tally.usage.raw.v1`.",
    "Load test: 5,000 events/s accepted with p99 < 50 ms on the local stack.",
    "Events older than the closed period follow the meter's late-event policy (REJECT → 400 per item in a `rejected` list)."])
st("602", "Aggregator windowed rollups", "WORK", 8, "S10", ["TLY-005", "TLY-003"], "FR-MET-03, NFR-COR-03, ADR-015, ADR-016", 8,
   "As the platform, I want raw usage rolled up exactly once per window, so that invoices charge the right quantity.", None,
   ["Tumbling 5-minute windows by event time with a 2-minute allowed lateness; SUM, MAX and UNIQUE_COUNT aggregations per meter.",
    "Duplicates by `event_id` within the dedup horizon are counted once; state checkpoints to the compacted topic survive restart (kill -9 test: totals unchanged).",
    "Each closed window emits `usage.rollup` with a deterministic `rollup_key`; a late event re-emits the same key with the corrected quantity.",
    "Watermark lag metric `tally_aggregator_watermark_lag_seconds` exported; p95 < 10 s at 5,000 ev/s.",
    "Aggregator never writes the core database."])
st("603", "Rollup ingestion, meters and usage summary", "CORE", 5, "S10", ["TLY-601"], "FR-MET-04, FR-MET-05", 8,
   "As a tenant, I want current-period usage and projections per customer, so that I and my customers can anticipate charges.", None,
   ["The metering consumer upserts `usage_rollups` by `rollup_key` via `kernel.inbox` dedup; replaying the topic from the beginning changes nothing.",
    "`POST/GET /v1/meters` manage meters; meter keys are unique per tenant.",
    "`GET /v1/usage/summary` returns actual, projected (linear on elapsed period), included and projected overage charge.",
    "Crossing a configured threshold emits `usage.threshold_crossed` once per period.",
    "The period-close job sets `closed_at` so billing uses only closed rollups."])
st("604", "Usage explorer screen", "WEB", 5, "S10", ["TLY-006"], "FR-MET-04", 8,
   "As a tenant admin, I want to see usage against what is included, so that I can spot overages early.", "UsageExplorer",
   ["Meter and customer pickers; cumulative chart with actual (solid) and projected (dashed) lines and the included-quota line.",
    "Summary shows actual, projected, included and projected overage in money.",
    "Recent events table with virtualized rows.",
    "Chart has an accessible data table alternative."])

# ---------------- E7 ----------------
st("701", "Payment processor port with Stripe test and simulator adapters", "CORE", 8, "S11", ["TLY-404"], "FR-PAY-02, ADR-017", 9,
   "As the platform, I want processors behind one port, so that payment logic does not depend on a vendor.", None,
   ["`PaymentProcessor` port: `charge`, `refund`, `status`, `setupToken`; both adapters pass one shared contract test suite.",
    "Simulator behavior is keyed by token suffix (`ok`, `decline_51`, `timeout`, `dup_settle`) as in `contracts/fixtures/tenants.json`.",
    "Every call carries the processor idempotency key `<payment_id>-<attempt_no>`; retrying the same attempt never double-charges in the simulator.",
    "Timeouts are 5 s with no retry inside the request; the adapter returns `Unknown`, never a guess.",
    "Processor webhooks (Stripe test) are verified by signature and deduped by processor event id."])
st("702", "Payments API and async outcome resolution", "CORE", 5, "S11", ["TLY-701", "TLY-202"], "FR-PAY-01, FR-PAY-03, NFR-COR-03", 9,
   "As a tenant, I want to charge customers safely, so that I get paid exactly once.", None,
   ["`POST /v1/payments` requires Idempotency-Key, writes PROCESSING, calls the processor outside the transaction, then records the attempt and outcome.",
    "Success posts Dr Cash-clearing / Cr Accounts receivable and marks the invoice PAID when fully covered; emits `payment.succeeded`.",
    "`Unknown` outcomes stay PROCESSING; the status poller (every 5 min) or processor webhook resolves them; no ledger entry until resolved.",
    "`GET /v1/payments?status=` and `GET /v1/payments/summary` (collected, success rate, refunded, failed) are served from indexed queries/read models.",
    "Chaos test: processor times out on 30 % of calls; after resolution, ledger totals equal processor totals."])
st("703", "Dunning schedules", "CORE", 5, "S11", ["TLY-702", "TLY-501"], "FR-PAY-04", 9,
   "As a tenant, I want failed payments retried on a schedule, so that I recover revenue without manual work.", None,
   ["A failed payment creates a dunning schedule from the tenant policy (default day 1, 3, 5, 7).",
    "Each step is a new attempt with a new processor idempotency key; success ends dunning and reactivates a PAST_DUE subscription.",
    "Exhausted dunning sets the subscription PAST_DUE and emits `invoice.overdue`.",
    "The dunning job is idempotent per (payment, step) and advanced correctly by test clocks."])
st("704", "Refunds", "CORE", 3, "S11", ["TLY-702"], "FR-PAY-05", 9,
   "As a finance user, I want full and partial refunds, so that I can make customers whole.", None,
   ["`POST /v1/refunds` with Idempotency-Key refunds up to the remaining refundable amount; over-refund returns 409 with the remaining amount.",
    "Each refund posts the reversing entries and sets payment status REFUNDED or PARTIALLY_REFUNDED.",
    "`payment.refunded` is emitted with the refund id.",
    "Concurrent partial refunds cannot exceed the payment amount (lock test with 20 parallel requests)."])
st("705", "Payments screen", "WEB", 5, "S11", ["TLY-006"], "FR-PAY-03, FR-PAY-05, NFR-FE-03", 9,
   "As a finance user, I want to see payments and act on them, so that I can resolve failures and refunds quickly.", "Payments",
   ["Summary tiles and status tabs; failed rows show the failure reason in words and next retry time.",
    "Row opens the drawer with attempts timeline and payment method (brand + last4 only).",
    "Refund requires typing the amount; partial refunds validate against the remaining amount before submit.",
    "Refund button disables while pending and uses one Idempotency-Key per intent."])
st("706", "Reports read models and attention items", "CORE", 5, "S12", ["TLY-702", "TLY-504"], "FR-DASH-01, NFR-API-01", 10,
   "As a tenant, I want fast dashboard numbers, so that Home loads instantly.", None,
   ["Projectors consume billing events into `revenue_daily` and `mrr_by_product` via `kernel.inbox`; a rebuild command replays events and produces identical totals.",
    "`/v1/reports/summary`, `/revenue?range=`, `/mrr-by-plan` p95 < 300 ms with 2 years of data for one tenant.",
    "Attention items are computed from failed payments, disabled endpoints, overdue invoices and trials ending, and can be dismissed per user.",
    "Read-model staleness is ≤ 10 s under normal load (metric)."])
st("707", "Home dashboard screen", "WEB", 5, "S12", ["TLY-006"], "FR-DASH-01, NFR-FE-02", 10,
   "As a tenant admin, I want a home page that tells me how the business is doing and what needs attention, so that I start each day in the right place.", "Main / Home",
   ["KPI cards (revenue this month, MRR, outstanding, failed payments) count up once on first load only; values are exact thereafter.",
    "Revenue chart with 7D/30D/12M toggle; line draws on range change; tooltip shows exact money.",
    "Attention list staggers in, supports dismiss and deep links; recent payments and upcoming renewals panels.",
    "Test-mode banner visible whenever the tenant is in test mode.",
    "LCP < 2.5 s and CLS < 0.1 on a throttled laptop profile."])
st("708", "Daily reconciliation job", "CORE", 5, "S17", ["TLY-702"], "FR-PAY-06, NFR-COR-05", 10,
   "As finance, I want the ledger reconciled against the processor daily, so that differences are caught within a day.", None,
   ["The job (02:00 UTC, idempotent per date) compares processor settlements with ledger cash-clearing postings per payment.",
    "Mismatches are classified TIMING, DUPLICATE, MISSING_CAPTURE or AMOUNT and stored in `ops.recon_mismatches`.",
    "The simulator's `dup_settle` token produces exactly one DUPLICATE mismatch in the integration test.",
    "A run summary (matched, mismatched, difference) is stored in `ops.recon_runs` and exported as a metric."])

# ---------------- E8 ----------------
st("801", "Operator realm, ops API security and hash-chained audit", "CORE", 8, "S13", ["TLY-102", "TLY-110"], "NFR-ADM-SEC-02, NFR-ADM-SEC-05, NFR-ADM-AUD-01, NFR-ADM-AUD-02, NFR-ADM-AUD-04, FR-ADM-GOV-03, ADR-022, ADR-023, ADR-026", 10,
   "As the platform, I want operator access fully separated and every access recorded tamper-evidently, so that insider risk is controlled.", None,
   ["`/ops/v1` on port 8081 accepts only `tally-operators` realm tokens with WebAuthn `amr`; tenant tokens get 401 and vice versa.",
    "Tenant-data endpoints require `X-Access-Reason`; the request sets the tenant context for that request only (RLS still applies).",
    "Every ops read of tenant data and every write appends to `ops.operator_audit_log` in the same transaction with `hash = sha256(prev_hash || canonical entry)`.",
    "A daily verification job recomputes the chain; tampering with one row in a test makes `GET /ops/v1/audit/verification` report `first_broken_seq`.",
    "RBAC matrix as code (deny by default) drives endpoint authorization; a generated test asserts every ops endpoint has an explicit rule."])
st("802", "Four-eyes approval framework", "CORE", 5, "S13", ["TLY-801"], "FR-ADM-GOV-01, FR-ADM-GOV-02, NFR-ADM-SEC-03, ADR-025", 10,
   "As a platform admin, I want high-risk actions to need a second operator, so that no single person can cause major harm.", None,
   ["Gated actions store `approval_requests` with payload, `payload_sha256`, impact text and 24 h expiry, and return 202 with the approval id.",
    "Approve requires step-up (`auth_time` < 5 min) and a different operator (DB CHECK + service check); the requester gets 403.",
    "`ApprovalExecutor` recomputes the hash and executes the stored payload, never a new request body; a hash mismatch aborts with 409.",
    "Expired requests become EXPIRED by job and cannot be approved.",
    "Approve, reject and execute are audited with both operator ids."])
st("803", "Approvals, audit log and operators screens", "OPSW", 8, "S13", ["TLY-007"], "FR-ADM-GOV-01, FR-ADM-GOV-03, FR-ADM-GOV-04", 11,
   "As an operator, I want to review requests, audit history and roles in the console, so that governance is visible and fast.", "AdminApprovals, AdminAudit, AdminOperators",
   ["Approvals queue shows action, requester, reason, impact and expiry; detail shows the exact stored payload.",
    "Approve triggers WebAuthn step-up; own requests show a disabled approve button with explanation.",
    "Audit log is filterable by operator, tenant, kind and text, shows the verification status badge, and exports CSV of the filtered range.",
    "Operators screen lists roles and pending role requests; requesting a role creates an approval."])
st("804", "Ops tenants API and overview", "CORE", 5, "S14", ["TLY-801", "TLY-802"], "FR-ADM-TEN-01, FR-ADM-TEN-02, FR-ADM-TEN-03, FR-ADM-TEN-04, FR-ADM-TEN-05, FR-TEN-03", 11,
   "As an operator, I want to find tenants that need attention and act safely, so that I resolve issues before customers notice.", None,
   ["`GET /ops/v1/tenants` supports views (NEEDS_ATTENTION, ALL, SCALE, SILO, SUSPENDED), search and health sort; p95 < 300 ms over 10k tenants on the replica.",
    "Contact data is masked; `reveal=true` returns it and writes a reveal audit entry.",
    "Suspend creates an approval; on execution the tenant becomes SUSPENDED: tenant API writes return 423, reads work, webhook deliveries pause (HELD).",
    "`GET /ops/v1/overview` returns platform KPIs and the attention queue; acknowledging an item is audited.",
    "Every tenant-data response is audited with the provided reason."])
st("805", "Ops tenants and overview screens", "OPSW", 5, "S14", ["TLY-007"], "FR-ADM-TEN-01, FR-ADM-TEN-02, FR-ADM-TEN-03, NFR-ADM-PER-02", 11,
   "As an operator, I want a dense tenant table and overview, so that I can scan the fleet quickly.", "AdminOverview, AdminTenants",
   ["Overview shows KPIs and the attention queue with deep links.",
    "Tenants table: saved views, search, health bars, signals; virtualized at 60 fps for 10k rows.",
    "Opening a tenant asks for an access reason once per tenant per session and sends it in `X-Access-Reason`.",
    "Suspend shows exact impact (tenant, active subscriptions, endpoints) and creates an approval."])
st("806", "Impersonation with token exchange", "CORE", 5, "S15", ["TLY-802", "TLY-103"], "FR-ADM-IMP-01, FR-ADM-IMP-02, FR-ADM-IMP-03, FR-ADM-IMP-04, FR-ADM-IMP-05, FR-OPS-01, ADR-024", 11,
   "As a support operator, I want to see what a tenant sees, time-boxed and visible to them, so that I can help without hidden access.", None,
   ["`POST /ops/v1/impersonations` (reason, 15/30/60 min) performs Keycloak token exchange; the token carries `act.sub = operator` and expires with the session.",
    "READ_ONLY tokens cannot call write endpoints (403); WRITE requires an approved request id.",
    "Every tenant audit entry during the session records actor = operator and on_behalf_of = tenant user.",
    "`GET /v1/account/impersonations` shows the tenant all sessions with operator name, reason, mode and write count.",
    "Ending or expiry revokes the token within 5 s."])
st("807", "Impersonation console screens", "OPSW", 5, "S15", ["TLY-007"], "FR-ADM-IMP-01, FR-ADM-IMP-03", 12,
   "As an operator, I want to start and end impersonation from the console, so that support sessions are deliberate and time-boxed.", "AdminImpersonation",
   ["Console form: tenant, reason, duration, mode; WRITE requires selecting an approved request.",
    "Active sessions list with live countdown and an end action that confirms revocation.",
    "Past sessions list per tenant with operator, reason, mode and write count.",
    "Starting a session opens the tenant app in a new tab with the exchanged token; the console never stores the token."])
st("808", "Platform health API and rate-limit overrides", "CORE", 5, "S16", ["TLY-801", "TLY-111"], "FR-ADM-OPS-01, FR-ADM-OPS-02, NFR-ADM-AVL-01", 12,
   "As an SRE, I want platform health and top tenants in one place, so that I can find the cause of an incident fast.", None,
   ["`/ops/v1/health/services` builds service tiles from Prometheus queries; data ≤ 15 s old.",
    "`/ops/v1/health/top-tenants` returns the top 10 by API share, rpm, ingest rate and webhook backlog over 5 minutes.",
    "`/ops/v1/alerts` mirrors Alertmanager; `/ops/v1/streams/health` pushes updates every 15 s.",
    "Health endpoints keep working when the core's tenant API is down (they read Prometheus directly).",
    "`POST /ops/v1/tenants/{id}/rate-limit` sets a temporary override with expiry, audited."])
st("809", "Health, webhook fleet and jobs screens", "OPSW", 8, "S16", ["TLY-007"], "FR-ADM-OPS-01, FR-ADM-OPS-03, FR-ADM-OPS-05", 13,
   "As an SRE, I want live health, fleet and job views, so that I can operate without Grafana for common tasks.", "AdminHealth, AdminFleet, AdminJobs",
   ["Health: service tiles with sparklines and thresholds, top-tenants table, alerts list; live via SSE.",
    "Fleet: backlog and DLQ by tenant; bulk replay shows the dry-run (events, endpoints, estimated time) before starting, then progress.",
    "Jobs: schedule, last status, duration and history dots; re-run form asks tenant/date and reason.",
    "Stale data (> 30 s) shows a 'stale' label."])
st("810", "Fleet, DLQ replay and job ops APIs", "WORK", 5, "S16", ["TLY-306", "TLY-307"], "FR-ADM-OPS-03, FR-ADM-OPS-04, FR-ADM-OPS-05, FR-ADM-OPS-06", 12,
   "As an SRE, I want to replay a tenant's DLQ safely and re-run jobs, so that I can recover from incidents without scripts.", None,
   ["Dispatcher internal API provides fleet backlog/DLQ counts per tenant and DLQ replay with `dry_run` (count, endpoints, estimate) and throttled execution (≤ 20/s per tenant).",
    "Replay progress is queryable; replays are idempotent per Idempotency-Key.",
    "Core proxies these at `/ops/v1/webhooks/*` and `/ops/v1/replays/{id}` with audit.",
    "`/ops/v1/jobs` lists core jobs from `ops.job_runs`; re-run executes idempotently by (job, tenant, date) and returns the existing run if already succeeded."])
st("811", "Reconciliation, refunds and ledger explorer ops APIs", "CORE", 5, "S17", ["TLY-708", "TLY-802"], "FR-ADM-MON-01, FR-ADM-MON-02, FR-ADM-MON-03, FR-ADM-MON-04", 12,
   "As a finance operator, I want to resolve mismatches, issue refunds and inspect ledgers, so that money issues are closed with a trail.", None,
   ["List runs and mismatches; resolve requires classification and a note (≥ 5 chars), audited.",
    "Operator refunds ≤ $500 (configurable) execute immediately; above the threshold they create an approval.",
    "Ledger accounts and journal entries are read-only per tenant with reason header; no write endpoint exists (asserted by route test).",
    "All amounts in responses are Money objects."])
st("812", "Recon, refunds and ledger explorer screens", "OPSW", 8, "S17", ["TLY-007"], "FR-ADM-MON-01, FR-ADM-MON-02, FR-ADM-MON-03", 13,
   "As a finance operator, I want console screens for reconciliation, refunds and ledgers, so that I can work money issues end to end.", "AdminRecon, AdminRefunds, AdminLedger",
   ["Recon: run calendar, mismatch table, resolve drawer with classification and note.",
    "Refunds: form with target, amount, reason; shows 'needs approval' when above the threshold before submit.",
    "Ledger: account balances and journal entries with postings; debits and credits aligned in mono columns.",
    "All three screens require an access reason for tenant data."])
st("813", "Plans, limits and feature flags ops API", "CORE", 5, "S18", ["TLY-801"], "FR-ADM-CFG-01, FR-ADM-CFG-02, FR-ADM-CFG-03", 12,
   "As a platform admin, I want versioned plans and targeted flags with a dry run, so that config changes never surprise tenants.", None,
   ["Creating a plan version with `dry_run=true` returns the diff and affected tenant count without writing.",
    "Migrating tenants between versions is idempotent and audited; tenants keep limits until migrated.",
    "Flags support targets ALL, PLAN, TIER, TENANT, COHORT and rollout 0/10/25/50/100 %; `dry_run` returns affected tenants.",
    "Flag evaluation is deterministic per tenant (hash bucketing) and cached ≤ 30 s."])
st("814", "Plans and flags screens", "OPSW", 5, "S18", ["TLY-007"], "FR-ADM-CFG-01, FR-ADM-CFG-02, FR-ADM-CFG-03", 13,
   "As a platform admin, I want to edit plans and flags with a visible diff, so that I know the impact before saving.", "AdminPlans, AdminFlags",
   ["Plans editor shows the current version and a side-by-side diff with affected tenant count before save.",
    "Flags list with targeting chips and rollout selector; save shows affected tenants from dry run.",
    "Both require a reason and show the resulting audit entry after save.",
    "Keyboard-complete."])

st("815", "Impersonation banner and history in the tenant app", "WEB", 3, "S15", ["TLY-006"], "FR-ADM-IMP-05, NFR-ADM-UX-02", 12,
   "As a tenant user, I want to see clearly when Tally staff are in my account, so that I can trust what happens there.", "Main / Home (impersonation banner)",
   ["When the session token carries an `act` claim, every page shows a non-dismissible banner with operator name, mode and remaining time.",
    "The banner cannot be hidden by CSS overrides from branding and stays above the test-mode banner.",
    "Settings lists impersonation history from `GET /v1/account/impersonations`.",
    "Write controls are disabled with an explanation during READ_ONLY sessions."])

# ---------------- E9 ----------------
st("901", "Observability: traces, dashboards, SLOs and runbooks", "PLAT", 5, "—", ["TLY-002", "TLY-301", "TLY-305"], "NFR-OBS-01, NFR-OBS-02, NFR-OBS-03, NFR-OBS-04", 13,
   "As an operator, I want one trace per request across services and per-tenant dashboards, so that incidents are diagnosed in minutes.", None,
   ["A request that finalizes an invoice produces one trace spanning core, Kafka, dispatcher and the endpoint call (Tempo query in the test).",
    "Grafana dashboards: API RED, outbox, dispatcher (backlog, attempts, fairness), aggregator, payments, per-tenant view.",
    "SLOs defined for API availability and webhook delivery with burn-rate alerts; each alert links a runbook in docs/runbooks/.",
    "A CI check fails if a metric uses a `tenant_id` label outside the allow-list."])
st("902", "Load suite with skewed tenants", "PLAT", 5, "—", ["TLY-601", "TLY-702", "TLY-305"], "NFR-PER-01, NFR-PER-02, NFR-PER-03, NFR-FAIR-01, NFR-FAIR-04", 14,
   "As the tech lead, I want repeatable load tests with a noisy neighbor, so that performance and fairness claims are measured.", None,
   ["k6 scenarios: writes 200 rps, reads 500 rps, ingest 5,000 ev/s, with 1,000 tenants where one tenant sends 50 % of traffic.",
    "Thresholds from docs/02 §2.2 are k6 thresholds; the run fails when any is missed.",
    "Results (p50/p95/p99 per tenant class) are published as a Markdown report artifact.",
    "`make load` runs a 5-minute smoke version locally."])
st("903", "Chaos and resilience suite", "PLAT", 5, "—", ["TLY-306", "TLY-702", "TLY-602"], "NFR-COR-02, NFR-COR-03, NFR-AVL-03, NFR-AVL-02", 14,
   "As the tech lead, I want failure injected on purpose, so that correctness under failure is proven, not assumed.", None,
   ["Scenarios in docs/08 §7 run with Toxiproxy and container kills; each asserts its invariant automatically.",
    "Broker kill during load: 0 lost events, 0 duplicate deliveries per (event, endpoint).",
    "Processor timeout storm: ledger = processor after resolution.",
    "Aggregator kill -9: rollup totals unchanged.",
    "`make chaos` runs the suite in < 20 minutes."])
st("904", "Security suite: cross-tenant, SSRF, secrets, DAST", "PLAT", 5, "—", ["TLY-102", "TLY-303"], "NFR-SEC-01, NFR-SEC-02, NFR-SEC-04, NFR-SEC-06", 14,
   "As the tech lead, I want isolation and common attack paths tested automatically, so that regressions cannot ship.", None,
   ["`CrossTenantAccessIT` is generated from `contracts/openapi.yaml`: for every path with an id, tenant B using tenant A's ids gets 404; for every list, B sees none of A's objects.",
    "SSRF suite covers private ranges, IPv6, decimal/octal IP encodings, redirects and DNS rebinding.",
    "Log scan asserts no API key, webhook secret, token or email in plain text across a full E2E run.",
    "OWASP ZAP baseline against web and core has 0 high findings."])
st("905", "Tenant data export and crypto-shred offboarding", "CORE", 8, "—", ["TLY-802", "TLY-403"], "FR-TEN-06, FR-TEN-07, NFR-SEC-05, NFR-CMP-01, ADR-020", 14,
   "As a tenant, I want to export my data and have it destroyed when I leave, so that my customers' data is not kept after I go.", None,
   ["`POST /v1/account/exports` produces a ZIP of JSON Lines for every tenant table within 1 h for 1M rows; the link expires after 7 days.",
    "Offboarding (ops, four-eyes) exports, then destroys the tenant DEK; afterwards encrypted fields are unreadable and the tenant cannot authenticate.",
    "Ledger entries remain (legal record) but reference only pseudonymous ids.",
    "The full flow completes within 30 days by policy and is audited."])
st("906", "Pool to silo live migration", "CORE", 8, "—", ["TLY-905", "TLY-801"], "FR-OPS-03, FR-ADM-TEN-08, ADR-021", 15,
   "As a platform admin, I want to move a large tenant to its own database without downtime, so that enterprise tenants get stronger isolation.", None,
   ["Migration (four-eyes) copies the tenant's rows to a dedicated database via logical replication filtered by tenant_id.",
    "Writes pause ≤ 5 s during cutover; the tenant routing table switches the tenant's datasource; no request fails with 5xx during the drill.",
    "Row counts and ledger balances match between source and target before cutover.",
    "Rollback within 15 minutes is rehearsed and documented in a runbook."])
st("909", "Accessibility and motion audit", "WEB", 3, "—", ["TLY-707", "TLY-506"], "NFR-FE-01, NFR-ADM-UX-04", 14,
   "As a user with assistive technology, I want every screen usable by keyboard and screen reader, so that I can do my job.", None,
   ["axe reports 0 violations on all 16 tenant and 14 operator screens in CI.",
    "Every screen has a keyboard-only Playwright journey.",
    "Reduced-motion snapshots exist for every animated component.",
    "Status indicators are verified to include text or icon, not color alone."])
st("910", "Backup, restore and zero-downtime migration drill", "PLAT", 3, "—", ["TLY-002"], "NFR-AVL-04, NFR-AVL-05", 15,
   "As the tech lead, I want restore and migration procedures rehearsed, so that data loss and downtime stay within targets.", None,
   ["WAL archiving + nightly base backup configured; a restore drill to a point in time completes in < 1 h with ≤ 5 min data loss.",
    "An expand-migrate-contract column rename runs under k6 load with 0 failed requests.",
    "Runbooks for both are in docs/runbooks/ and linked from alerts.",
    "Staging on k3d with the Helm chart comes up with `make staging-up`."])
